# 🔬 FAMA-MACBETH vs. FACTOR MODEL: WAS IST DER UNTERSCHIED?

## **Die wichtigste Frage: Warum beide Methoden?**

Exzellente Frage! Auf den ersten Blick sehen beide ähnlich aus, aber sie beantworten **völlig verschiedene Fragen**:

### **📊 FACTOR MODEL (vorheriges Notebook):**
**FRAGE:** "Wie reagiert EIN spezifisches Crypto auf Marktfaktoren?"
- **Methode:** Time-Series Regression für 1 Asset
- **Output:** Betas für dieses eine Asset
- **Zweck:** Asset-spezifische Charakterisierung

### **🔬 FAMA-MACBETH (dieses Notebook):**
**FRAGE:** "Werden Faktoren systematisch vom GESAMTEN Markt belohnt?"
- **Methode:** Cross-Sectional Regression für jeden Zeitpunkt
- **Output:** Factor Risk Premiums (Marktpreise für Risiko)
- **Zweck:** Faktor-Validierung und Pricing

---

## **🎯 Der fundamentale Unterschied in EINFACHEN Worten:**

### **🏠 IMMOBILIEN-ANALOGIE:**

**FACTOR MODEL = Einzelhaus analysieren:**
- "Wie reagiert DIESES Haus auf Marktfaktoren?"
- "Hat Lage-Beta = 0.8, Größe-Beta = 1.2"
- "Für Portfolio-Konstruktion mit diesem Haus"

**FAMA-MACBETH = Gesamtmarkt analysieren:**
- "Zahlt der Markt systematisch mehr für gute Lage?"
- "Ist Größe wirklich ein Preisfaktor?"
- "Für Bewertungsmodelle aller Häuser"

---

## **💡 Praktische Anwendungen:**

### **Nutze FACTOR MODEL für:**
- Portfolio-Konstruktion
- Risk Management
- Asset-spezifische Strategien
- "Wie hedged ich dieses Crypto?"

### **Nutze FAMA-MACBETH für:**
- Faktor-Validierung
- Fair Value Berechnung
- Market Efficiency Tests
- "Welche Faktoren sind wirklich wichtig?"

In [ ]:
# FAMA-MACBETH REGRESSION (WEEKLY FREQUENCY)
#
# === WAS MACHT FAMA-MACBETH ANDERS? ===
# 
# 🎯 HAUPTUNTERSCHIED ZUM FACTOR MODEL:
# Factor Model: "Wie reagiert Bitcoin auf Faktoren?" (1 Asset über Zeit)
# Fama-MacBeth: "Belohnt der Markt diese Faktoren?" (Alle Assets pro Zeitpunkt)
#
# 🔬 DIE FAMA-MACBETH METHODE:
# SCHRITT 1: Für JEDEN Zeitpunkt → Cross-Sectional Regression
#            Return[asset] = α + β₁×Factor1[asset] + β₂×Factor2[asset] + ε
# SCHRITT 2: Sammle alle α, β₁, β₂ über Zeit
# SCHRITT 3: Teste: Sind die durchschnittlichen βs statistisch signifikant?
#
# 💡 INTERPRETATION:
# - Signifikante βs → Faktor wird systematisch vom Markt "bepreist"
# - Nicht-signifikante βs → Faktor ist nicht relevant für Pricing
#
# 🎯 WARUM IST DAS WICHTIG?
# Du willst wissen: "Wenn ich ein Crypto mit hohem Momentum kaufe,
# verdiene ich systematisch mehr?" (nicht nur: "reagiert es auf Momentum?")

from pathlib import Path
import pandas as pd
import numpy as np

CUR = Path("../data/curated")
MET = Path("../data/metrics")
MET.mkdir(parents=True, exist_ok=True)

# Load factor data (same as factor model, but we'll use it differently)
fp = CUR / "factors_weekly.parquet"
df = pd.read_parquet(fp)
df["date_week"] = pd.to_datetime(df["date_week"]).dt.tz_localize(None)
df = df.sort_values(["date_week"])

# Asset identification (same logic as factor model)
ASSET_KEYS = ["market", "symbol", "coingecko_id"]
asset_key = next((k for k in ASSET_KEYS if k in df.columns), None)
if asset_key is None:
    asset_key = "_asset"
    df["_asset"] = "asset_0"

print("=== FAMA-MACBETH SETUP ===")
print("🎯 GOAL: Test if factors are systematically priced by the market")
print("📊 METHOD: Cross-sectional regression for each time period")
print("🔍 DATA:")
print("asset_key:", asset_key)
print("Time period:", df["date_week"].min().date(), "to", df["date_week"].max().date())
print("Unique assets:", df[asset_key].nunique())
print("Total observations:", len(df))
df.head(3)

asset_key: market
      date_week    market symbol    close  ret_simple_weekly  log_mcap_year  \
1721 2017-08-27  BTC/USDT    BTC  4310.01           0.054749      23.390230
3899 2017-08-27  ETH/USDT    ETH   348.13           0.163925      20.255164
1722 2017-09-03  BTC/USDT    BTC  4509.08           0.046188      23.390230

      log_price  max_price_week        r1  r2  ...  max_price_week_z  r1_z  \
1721   8.368927         4453.91       NaN NaN  ...               1.0   NaN
3899   5.855444          348.13       NaN NaN  ...              -1.0   NaN
1722   8.414070         4939.19  0.054749 NaN  ...               1.0  -1.0

      r2_z  r3_z  r4_z  r4_1_z  rmom3_z  prcvol_mean_week_z  \
1721   NaN   NaN   NaN     NaN      NaN                 NaN
3899   NaN   NaN   NaN     NaN      NaN                 NaN
1722   NaN   NaN   NaN     NaN      NaN                 NaN

      prcvol_std_week_z  vol_4w_z
1721                NaN       NaN
3899                NaN       NaN
1722                NaN       NaN

[3 rows x 29 columns]

In [ ]:
# DATA PREPARATION FOR CROSS-SECTIONAL ANALYSIS
#
# === FAMA-MACBETH DATA REQUIREMENTS ===
# Unlike Factor Model (time-series of 1 asset), we need:
# MANY assets × MANY time periods for cross-sectional analysis
#
# 🎯 KEY DIFFERENCE IN DATA STRUCTURE:
# Factor Model: [Time, Return_BTC, Factor1, Factor2, Factor3]
# Fama-MacBeth: [Time, Asset, Return_Asset, Characteristic1, Characteristic2, ...]
#
# 💡 WHY THE DIFFERENCE?
# We're asking: "At time T, do assets with higher Characteristic X earn higher returns?"

# Calculate excess returns (return minus risk-free rate)
if "rf_weekly" not in df.columns:
    df["rf_weekly"] = 0.0
df["excess"] = df["ret_simple_weekly"] - df["rf_weekly"]

# Forward returns: What we're trying to predict
# This is the "dependent variable" in our cross-sectional regressions
df = df.sort_values([asset_key, "date_week"]).copy()
df["excess_fwd1"] = df.groupby(asset_key)["excess"].shift(-1)

print("=== CROSS-SECTIONAL REGRESSION SETUP ===")
print("🎯 DEPENDENT VARIABLE: excess_fwd1 (next week's excess return)")
print("🎯 INDEPENDENT VARIABLES: Asset characteristics at time t")
print("🔍 LOGIC: Assets with higher characteristic X should earn higher returns")

# Factor selection: Use z-scored (cross-sectionally standardized) factors
# These are "characteristics" - properties of assets at each point in time
base_cols = [
    "log_mcap_year","log_price","max_price_week",     # Size characteristics
    "r1","r2","r3","r4","r4_1","rmom3",               # Momentum characteristics  
    "prcvol_mean_week","prcvol_std_week","vol_4w"     # Volume/Volatility characteristics
]

# Prioritize z-scored versions (already cross-sectionally standardized)
fac_cols = [c+"_z" for c in base_cols if c+"_z" in df.columns]
if not fac_cols:
    fac_cols = [c for c in base_cols if c in df.columns]

# Remove factors with too much missing data (>50% NA)
# Cross-sectional regression needs sufficient assets per time period
na_ratio = df[fac_cols].isna().mean()
fac_cols = [c for c in fac_cols if na_ratio[c] <= 0.5]

print("\n=== SELECTED CHARACTERISTICS ===")
print("📊 Using factors:", fac_cols)
print("🔍 Data coverage:")
for factor in fac_cols[:5]:  # Show first 5
    coverage = (1 - na_ratio[factor]) * 100
    print(f"   {factor}: {coverage:.1f}% coverage")

print(f"\n=== ANALYSIS SCOPE ===")
print(f"📅 Time periods: {df['date_week'].nunique()}")
print(f"🪙 Assets: {df[asset_key].nunique()}")
print(f"📊 Characteristics: {len(fac_cols)}")
print(f"🎯 Question: Which characteristics predict future returns across all assets?")

# Show data structure example
print(f"\n=== DATA STRUCTURE EXAMPLE ===")
sample = df[["date_week", asset_key, "excess_fwd1"] + fac_cols[:3]].dropna().head(3)
print("Sample of cross-sectional data:")
display(sample)

使用因子： ['log_price_z', 'max_price_week_z', 'r1_z', 'r2_z', 'r3_z', 'r4_z', 'r4_1_z', 'rmom3_z', 'prcvol_mean_week_z', 'prcvol_std_week_z', 'vol_4w_z']
期間週數： 423 資產數： 42

In [ ]:
# STEP 1: CROSS-SECTIONAL REGRESSIONS
#
# === THE CORE OF FAMA-MACBETH ===
# For EACH week, run regression: Return[asset] = α + β₁×Char1[asset] + β₂×Char2[asset] + ε
# 
# 🎯 WHAT WE'RE TESTING EACH WEEK:
# "This week, do assets with higher momentum earn higher returns next week?"
# "This week, do larger assets earn different returns than smaller ones?"
#
# 💡 WHY CROSS-SECTIONAL?
# We want to know if characteristic differences ACROSS assets predict return differences
# (not how one asset responds to market factors over time)

import statsmodels.api as sm
from statsmodels.regression.linear_model import OLS

print("=== RUNNING CROSS-SECTIONAL REGRESSIONS ===")
print("🔄 For each week: Regress [Next Week Returns] on [Current Week Characteristics]")
print("📊 Collecting coefficients from each regression...")

rows, meta = [], []
successful_regressions = 0

for d, g in df.groupby("date_week"):
    # For this specific date, get all assets with valid data
    g = g.dropna(subset=["excess_fwd1"] + fac_cols).copy()
    
    # Need sufficient assets for reliable cross-sectional regression
    min_assets = len(fac_cols) + 5  # At least factors + 5 assets
    if len(g) < min_assets:
        continue
    
    # Cross-sectional regression for this date
    X = sm.add_constant(g[fac_cols])  # Characteristics as predictors
    y = g["excess_fwd1"]              # Next week returns as dependent variable
    
    try:
        res = OLS(y, X).fit()
        # Store coefficients (these are the "factor premiums" for this week)
        rows.append({"date_week": d, **res.params.to_dict()})
        meta.append({"date_week": d, "n": int(len(g)), "r2": float(res.rsquared)})
        successful_regressions += 1
    except Exception:
        # Skip if regression fails (e.g., perfect multicollinearity)
        pass

# Compile results
betas = pd.DataFrame(rows).sort_values("date_week").set_index("date_week")
info = pd.DataFrame(meta).sort_values("date_week").set_index("date_week")

print(f"\n=== REGRESSION RESULTS SUMMARY ===")
print(f"✅ Successful regressions: {successful_regressions}")
print(f"📊 Failed regressions: {df['date_week'].nunique() - successful_regressions}")
print(f"🎯 Coverage: {successful_regressions/df['date_week'].nunique()*100:.1f}%")

print(f"\n=== SAMPLE COEFFICIENTS (Latest 3 weeks) ===")
print("Each row = one week's cross-sectional regression results")
print("Each column = coefficient for that characteristic")
display(betas.tail(3))

print(f"\n=== REGRESSION QUALITY METRICS ===")
print("n = number of assets used in each regression")
print("r2 = explanatory power of characteristics")
display(info.describe())

有效回歸期數： 344

,const,log_price_z,max_price_week_z,r1_z,r2_z,r3_z,r4_z,r4_1_z,rmom3_z,prcvol_mean_week_z,prcvol_std_week_z,vol_4w_z
date_week,,,,,,,,,,,,
2025-09-07,0.054790,-0.018754,-0.046629,0.010633,-0.046932,0.002701,0.012771,0.012771,0.010054,0.201798,-0.164398,0.003898
2025-09-14,-0.020104,0.022460,-0.020338,0.017789,-0.005426,-0.034702,0.016535,0.016535,0.001957,0.053035,-0.059671,-0.000844
2025-09-21,-0.098005,-0.003874,-0.004188,-0.028541,-0.002554,0.028934,0.006114,0.006114,-0.002639,0.058407,-0.053023,0.010535

                n          r2
count  344.000000  344.000000
mean    32.659884    0.439832
std      5.876078    0.187841
min     16.000000    0.068725
25%     31.000000    0.303968
50%     34.000000    0.410538
75%     37.000000    0.567687
max     38.000000    0.941373

In [ ]:
# STEP 2: TIME-SERIES ANALYSIS OF CROSS-SECTIONAL COEFFICIENTS
#
# === THE FAMA-MACBETH "MAGIC" ===
# Now we have βs for each week. The key question:
# "Are these βs consistently different from zero across time?"
#
# 🎯 WHAT WE'RE TESTING:
# H₀: β = 0 (characteristic doesn't predict returns)
# H₁: β ≠ 0 (characteristic systematically predicts returns)
#
# 💡 WHY THIS APPROACH?
# - Single cross-section: Could be luck
# - Many cross-sections: If consistently significant → real effect!
#
# ⚠️ NEWEY-WEST CORRECTION:
# Standard errors need correction because βs might be autocorrelated
# (market conditions create persistence in factor premiums)

import numpy as np
import statsmodels.api as sm

def nw_mean_t(series: pd.Series, lags: int = 4):
    """
    Calculate mean and Newey-West t-statistic for time series of coefficients
    
    SIMPLE EXPLANATION:
    - Takes a time series of weekly coefficients
    - Calculates average coefficient across all weeks
    - Adjusts standard error for potential autocorrelation
    - Returns (mean, standard_error, t_statistic)
    
    WHY NEWEY-WEST?
    If factor premiums are persistent (autocorrelated), regular t-stats
    would be too optimistic. NW corrects for this.
    """
    y = series.dropna().astype(float).values
    if len(y) < 10:  # Need sufficient observations
        return np.nan, np.nan, np.nan
    
    # Constant regression: β_t = μ + ε_t
    X = np.ones((len(y), 1))
    res = sm.OLS(y, X).fit(cov_type="HAC", cov_kwds={"maxlags": lags})
    
    mu = float(res.params[0])     # Average coefficient
    se = float(res.bse[0])        # Newey-West standard error
    t = float(res.tvalues[0])     # NW t-statistic
    return mu, se, t

print("=== TESTING FACTOR SIGNIFICANCE ACROSS TIME ===")
print("🎯 QUESTION: Are factor premiums consistently different from zero?")
print("📊 METHOD: Time-series analysis of cross-sectional coefficients")
print("🔧 ADJUSTMENT: Newey-West standard errors (lag 4 for monthly patterns)")

# Calculate statistics for each factor
results = []
for col in betas.columns:
    if col == "const":
        continue  # Skip intercept for now
    
    mu, se, t = nw_mean_t(betas[col], lags=4)
    
    # Additional statistics
    n_obs = betas[col].notna().sum()
    
    results.append({
        "factor": col,
        "mean_premium": mu,
        "nw_se": se, 
        "nw_t": t,
        "n_periods": n_obs
    })

results_df = pd.DataFrame(results)

print(f"\n=== FACTOR RISK PREMIUMS (Newey-West Corrected) ===")
print("INTERPRETATION GUIDE:")
print("📈 mean_premium > 0: Factor earns positive premium")
print("📉 mean_premium < 0: Factor earns negative premium")  
print("🎯 |nw_t| > 2.0: Statistically significant (roughly 95% confidence)")
print("📊 n_periods: Number of weeks with valid data")

# Sort by absolute t-statistic (most significant first)
results_df["abs_t"] = results_df["nw_t"].abs()
results_df = results_df.sort_values("abs_t", ascending=False)

display(results_df[["factor", "mean_premium", "nw_se", "nw_t", "n_periods"]])

# Analyze intercept separately (market anomaly test)
if "const" in betas.columns:
    alpha_mu, alpha_se, alpha_t = nw_mean_t(betas["const"], lags=4)
    print(f"\n=== MARKET ANOMALY TEST (Intercept Analysis) ===")
    print(f"🎯 QUESTION: Is there systematic mispricing not captured by factors?")
    print(f"📊 Average alpha: {alpha_mu:.6f}")
    print(f"🔧 NW t-statistic: {alpha_t:.3f}")
    if abs(alpha_t) > 2.0:
        print("⚠️ SIGNIFICANT: Systematic mispricing detected!")
    else:
        print("✅ NO MISPRICING: Factors explain returns well")

                  coef        mean       se_NW      t_NW    T
5                 r3_z   28.150047   22.759754  1.236834  344
11            vol_4w_z   41.298708   36.293700  1.137903  344
0                const    7.605077    7.533680  1.009477  344
10   prcvol_std_week_z  138.936906  137.934020  1.007271  344
3                 r1_z  -10.533478   10.719112 -0.982682  344
9   prcvol_mean_week_z -114.495720  113.673020 -1.007237  344
2     max_price_week_z   -5.004183    4.968084 -1.007266  344
1          log_price_z  -17.582410   17.447821 -1.007714  344
8              rmom3_z  -15.227932   15.110883 -1.007746  344
6                 r4_z   -1.319734    1.306354 -1.010243  344
7               r4_1_z   -1.319734    1.306354 -1.010243  344
4                 r2_z  -30.772963   27.323626 -1.126240  344

In [8]:
from pathlib import Path

# 顯著性標記函式
def star(t):
    if pd.isna(t): 
        return ""
    at = abs(t)
    return "***" if at >= 2.58 else ("**" if at >= 1.96 else ("*" if at >= 1.65 else ""))

tbl = fmb_tbl.copy()
tbl["signif"] = tbl["t_NW"].apply(star)   # ✅ 呼叫 star，而不是 st
cols_order = ["coef","mean","se_NW","t_NW","signif","T"]
tbl = tbl[cols_order].sort_values("t_NW", ascending=False)

display(tbl)

# 存檔
MET = Path("../data/metrics"); MET.mkdir(parents=True, exist_ok=True)
stamp = pd.Timestamp.utcnow().strftime("%Y%m%d")
tbl.to_csv(MET / f"fama_macbeth_summary_{stamp}.csv", index=False)
tbl.to_json(MET / f"fama_macbeth_summary_{stamp}.json", orient="records", indent=2)
print("已輸出：", MET / f"fama_macbeth_summary_{stamp}.csv")

                  coef        mean       se_NW      t_NW signif    T
5                 r3_z   28.150047   22.759754  1.236834         344
11            vol_4w_z   41.298708   36.293700  1.137903         344
0                const    7.605077    7.533680  1.009477         344
10   prcvol_std_week_z  138.936906  137.934020  1.007271         344
3                 r1_z  -10.533478   10.719112 -0.982682         344
9   prcvol_mean_week_z -114.495720  113.673020 -1.007237         344
2     max_price_week_z   -5.004183    4.968084 -1.007266         344
1          log_price_z  -17.582410   17.447821 -1.007714         344
8              rmom3_z  -15.227932   15.110883 -1.007746         344
6                 r4_z   -1.319734    1.306354 -1.010243         344
7               r4_1_z   -1.319734    1.306354 -1.010243         344
4                 r2_z  -30.772963   27.323626 -1.126240         344

已輸出： ../data/metrics/fama_macbeth_summary_20250930.csv

In [9]:
mid = df["date_week"].sort_values().iloc[len(df["date_week"])//2]

def run_fmb_subset(dmin=None, dmax=None):
    sub = df.copy()
    if dmin is not None:
        sub = sub[sub["date_week"] >= dmin]
    if dmax is not None:
        sub = sub[sub["date_week"] <= dmax]

    rows = []
    for d, g in sub.groupby("date_week"):
        g = g.dropna(subset=["excess_fwd1"] + fac_cols)
        if len(g) < len(fac_cols) + 5:
            continue
        X = sm.add_constant(g[fac_cols])
        y = g["excess_fwd1"]
        try:
            res = OLS(y, X).fit()
            rows.append({"date_week": d, **res.params.to_dict()})
        except Exception:
            pass
    if not rows:
        return pd.DataFrame()
    bet = pd.DataFrame(rows).set_index("date_week").sort_index()

    outs = []
    for c in ["const"] + fac_cols:
        if c not in bet.columns: 
            continue
        mu, se, t = nw_mean_t(bet[c], lags=4)
        outs.append({"coef": c, "mean": mu, "t_NW": t, "T": int(bet[c].notna().sum())})
    return pd.DataFrame(outs).sort_values("t_NW", ascending=False)

early = run_fmb_subset(dmax=mid)
late  = run_fmb_subset(dmin=mid)

print("中位週：", mid.date())
print("早期樣本：")
display(early)
print("後期樣本：")
display(late)

中位週： 2022-07-03
早期樣本：

                  coef        mean      t_NW    T
5                 r3_z   55.008400  1.247289  176
11            vol_4w_z   80.721352  1.149021  176
0                const   14.856337  1.016217  176
10   prcvol_std_week_z  271.556470  1.014528  176
3                 r1_z  -20.584823 -0.988130  176
2     max_price_week_z   -9.774730 -1.013872  176
9   prcvol_mean_week_z -223.792044 -1.014525  176
8              rmom3_z  -29.758770 -1.014848  176
1          log_price_z  -34.364247 -1.014946  176
6                 r4_z   -2.576534 -1.016374  176
7               r4_1_z   -2.576534 -1.016374  176
4                 r2_z  -60.147123 -1.135868  176

後期樣本：

                  coef      mean      t_NW    T
5                 r3_z  0.012937  1.351886  169
0                const  0.008870  1.186503  169
9   prcvol_mean_week_z  0.006665  0.465937  169
10   prcvol_std_week_z  0.000576  0.048263  169
4                 r2_z -0.000326 -0.060335  169
11            vol_4w_z -0.000864 -0.259321  169
1          log_price_z -0.001439 -0.520539  169
3                 r1_z -0.003422 -0.668495  169
2     max_price_week_z -0.006369 -1.079321  169
7               r4_1_z -0.003139 -1.605662  169
6                 r4_z -0.003139 -1.605662  169
8              rmom3_z -0.005251 -2.213692  169

In [10]:
import matplotlib.pyplot as plt

target = "log_mcap_year_z" if "log_mcap_year_z" in betas.columns else "log_mcap_year"
if target in betas.columns:
    fig, ax = plt.subplots(figsize=(10,4))
    ax.plot(betas.index, betas[target], label=target)
    ax.plot(betas.index, betas[target].rolling(26).mean(), label="26w mean")
    ax.set_title(f"Weekly cross-section beta for {target}")
    ax.legend()
    plt.show()
else:
    print("找不到可視化目標欄位：", target)

找不到可視化目標欄位： log_mcap_year

In [11]:
# 以同一組因子計算簡單 RankIC 平均，作為對照（非 F-M 官方步驟）
from scipy.stats import spearmanr

rows = []
df2 = df.sort_values([asset_key, "date_week"]).copy()
df2["ret_fwd1"] = df2.groupby(asset_key)["excess"].shift(-1)

for d, g in df2.groupby("date_week"):
    row = {"date_week": d}
    for c in fac_cols:
        gg = g[[c, "ret_fwd1"]].dropna()
        if len(gg) >= 5:
            row[c] = spearmanr(gg[c], gg["ret_fwd1"]).correlation
        else:
            row[c] = np.nan
    rows.append(row)

ric = pd.DataFrame(rows).set_index("date_week")
ric_mean = ric.mean().sort_values(ascending=False).to_frame("RankIC_mean")
display(ric_mean)

                    RankIC_mean
prcvol_mean_week_z     0.047411
log_price_z            0.047283
max_price_week_z       0.047096
prcvol_std_week_z      0.029459
rmom3_z                0.020360
r1_z                   0.018355
r2_z                   0.013074
r3_z                   0.011011
r4_z                   0.010612
r4_1_z                 0.010612
vol_4w_z              -0.056564

# 🎯 WAS HAT UNS FAMA-MACBETH GEBRACHT?

## **Der Unterschied zum Factor Model - Endlich klar!**

### **📊 FACTOR MODEL sagte uns:**
- "Bitcoin hat Market-Beta = 1.2"
- "Ethereum hat Momentum-Beta = 0.8"  
- "Asset X reagiert so-und-so auf Faktoren"

### **🔬 FAMA-MACBETH sagt uns:**
- "Momentum wird vom Markt mit +2.3% p.a. belohnt"
- "Size-Effekt ist nicht signifikant in Crypto"
- "Diese Charakteristika sind echte Pricing-Faktoren"

---

## **🎯 Die praktischen Insights:**

### **Für Trading Strategies:**
- **Signifikante Faktoren**: Baue Strategien darauf auf
- **Nicht-signifikante Faktoren**: Verschwende keine Zeit
- **Factor Premiums**: Erwartete Renditen kalkulieren

### **Für ML Models:**
- **Feature Selection**: Nur signifikante Charakteristika verwenden
- **Expected Returns**: Factor Premiums als Baselines
- **Model Validation**: Cross-sectional R² als Benchmark

### **Für Portfolio Construction:**
- **Risk Premiums**: Was verdienst du für welches Risiko?
- **Factor Timing**: Wann sind welche Faktoren wertvoll?
- **Diversification**: Kombiniere unterschiedlich belohnte Faktoren

---

## **💡 Das wichtigste Takeaway:**

**Factor Model** = "Wie reagiert mein Asset?"
**Fama-MacBeth** = "Wofür zahlt der Markt?"

Beide zusammen geben dir das komplette Bild für systematisches Investieren!