In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('data with 3 flags.csv', low_memory=False)

In [5]:
df.shape

(56092, 739)

In [7]:
df.head()

,costat,curcd,datafmt,indfmt,consol,tic,datadate,gvkey,conm,cusip,cik,exchg,fyr,fic,fyrc,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc,closest flag,after flag include,Delist_Flag
0,A,USD,STD,INDL,C,AIR,2020-05-31,1004,AAR CORP,000361105,1750.0,11.0,5,USA,5,2019,NaN,22.9,92.2,69.3,-44.6,92.2,NaN,1438.7,NaN,0.0,37.2,0.0,0.0,-42.6,0.0,37.2,37.2,191.6,NaN,NaN,NaN,NaN,NaN,NaN,2079.0,25.7173,NaN,478.6,902.6,902.6,776.8,404.7,424.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.7,22.5,0.0,0.0,579.5,NaN,NaN,13.7,672.9,600.0,NaN,670.9,0.0,0.0,NaN,246.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.5,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.5,125.8,10.1,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.8,41.1,NaN,29.9,383.1,NaN,NaN,0.0,NaN,NaN,NaN,122.4,34.4,NaN,NaN,2079.0,1176.4,0.0,16.5,14.5,12.7,10.7,8.3,62.7,36.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.6,NaN,437.1,NaN,683.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.4,0.0,-42.6,0.0,22.1,229.1,-2.0,221.2,49.3,NaN,706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.7,282.7,0.0,0.0,3.5,0.0,0.0,0.0,3.5,64.9,61.4,0.0,0.0,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.6,136.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.4,0.1,0.0,0.0,-3.8,0.0,0.7,NaN,1728.7,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.7,-20.4,NaN,43.7,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.4,150.1,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.8,24.7,NaN,24.8,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.4,4.3,NaN,NaN,NaN,NaN,NaN,NaN,-3.5,-4.0,NaN,NaN,NaN,106.4,150.1,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.4,23.6,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.3,NaN,NaN,2089.3,NaN,NaN,NaN,NaN,-63.2,-0.20,-0.20,-6.8,-8.9,NaN,7.3,NaN,NaN,NaN,NaN,NaN,5.1,NaN,NaN,0.5,NaN,NaN,NaN,1.4,2.8,0.0,0.9,5.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.2,NaN,NaN,14.9,NaN,31.1,NaN,210.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,0.0,23.6,23.6,NaN,383.6,NaN,459.5,0.0,0.0,43.7,10.7,1.9,0.0,-1.3,444.5,52.1,52.1,NaN,NaN,NaN,NaN,NaN,24.8,8.6,-98.8,NaN,-1.2,0.0,-24.8,NaN,-36.1,NaN,4.1,NaN,NaN,24.7,NaN,0.0,NaN,0.0,NaN,1.1,NaN,0.0,0.0,0.0,0.5,NaN,NaN,NaN,NaN,-17.0,0,0,0
1,A,USD,STD,INDL,C,AIR,2021-05-31,1004,AAR CORP,000361105,1750.0,11.0,5,USA,5,2020,NaN,19.5,47.2,27.7,-18.3,47.2,NaN,937.0,NaN,0.0,33.9,0.0,0.0,-22.2,0.0,33.9,33.9,127.2,NaN,NaN,NaN,NaN,NaN,NaN,1539.7,27.5449,NaN,479.8,974.4,974.4,825.6,51.8,60.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.5,0.0,0.0,109.5,0.0,NaN,NaN,11.5,195.1,133.7,NaN,193.6,0.0,0.0,NaN,260.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.2,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.0,148.8,29.5,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.4,61.3,NaN,35.4,336.8,NaN,NaN,0.0,NaN,NaN,NaN,25.4,20.0,NaN,NaN,1539.7,565.3,0.0,13.7,11.9,9.9,8.8,7.7,52.0,32.9,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.3,NaN,380.1,NaN,640.3,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.4,0.0,-22.2,0.0,16.4,238.6,3.9,238.6,71.9,NaN,741.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.1,274.1,0.0,9.5,0.0,0.0,0.0,9.5,-9.5,44.5,54.0,0.0,0.7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.2,136.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.8,5.9,0.0,0.0,20.4,0.0,62.1,NaN,1364.6,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.9,-10.5,NaN,36.3,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.5,101.8,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,45.9,NaN,46.3,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.8,35.4,NaN,NaN,NaN,NaN,NaN,NaN,-12.1,-12.3,NaN,NaN,NaN,65.5,101.8,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.5,43.7,20.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.4,NaN,NaN,1651.4,3.30,0.09,0.09,4.3,16.1,0.82,0.82,28.6,37.6,NaN,9.2,NaN,NaN,NaN,NaN,NaN,9.8,NaN,NaN,8.4,NaN,NaN,NaN,5.2,3.4,0.0,1.2,18.2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.6,NaN,NaN,6.2,NaN,21.6,NaN,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.5,NaN,0.0,11.3,11.3,NaN,-364.5,NaN,-470.0,0.0,0.0,36.3,0.1,-0.2,0.3,0.0,-469.5,29.0,29.0,NaN,NaN,NaN,NaN,NaN,46.3,4.3,74.9,NaN,10.8,0.0,-0.5,NaN,105.2,NaN,0.0,NaN,NaN,-30.9,NaN,0.0,0.0,20.2,NaN,0.6,NaN,NaN,0.0,0.0,8.4,NaN,NaN,NaN,NaN,-3.3,0,0,0
2,A,USD,STD,INDL,C,AIR,2022-05-31,1004,AAR CORP,000361105,1750.0,11.0,5,USA,5,2021,NaN,16.2,53.9,37.7,-19.6,53.9,NaN,1007.2,NaN,0.0,33.1,0.0,0.0,-16.8,0.0,33.1,33.1,156.4,NaN,NaN,NaN,NaN,NaN,NaN,1573.9,29.2306,NaN,477.5,1034.5,1034.5,892.6,53.5,58.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.1,0.0,100.0,0.0,0.0,NaN,NaN,11.1,157.4,98.9,NaN,156.3,0.0,0.0,NaN,258.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.3,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.8,141.9,25.5,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,37.7,NaN,17.2,348.2,NaN,NaN,0.0,NaN,NaN,NaN,14.9,4.8,NaN,NaN,1573.9,539.4,0.0,13.6,12.4,11.0,9.2,8.5,54.7,25.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.5,NaN,349.2,NaN,607.5,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.8,0.0,-16.8,0.0,17.9,290.3,-2.8,287.6,119.2,NaN,820.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.1,289.1,0.0,20.0,0.0,0.0,0.0,20.0,-20.0,38.5,58.5,0.0,0.0,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.0,143.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.7,-6.7,0.0,0.0,5.4,0.0,77.4,NaN,1470.3,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.9,0.2,NaN,33.1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.2,149.3,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.5,77.9,NaN,78.5,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.7,78.1,NaN,NaN,NaN,NaN,NaN,NaN,-2.3,-2.4,NaN,NaN,NaN,116.2,149.3,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.1,77.1,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.1,NaN,NaN,1817.1,NaN,NaN,NaN,NaN,-6.4,0.01,0.01,0.3,0.2,NaN,8.2,NaN,NaN,NaN,NaN,NaN,17.9,NaN,NaN,8.7,NaN,NaN,NaN,11.0,4.3,0.0,2.6,26.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.8,NaN,NaN,7.3,NaN,32.2,NaN,197.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,NaN,0.0,17.3,17.3,NaN,-1.3,NaN,-9.5,0.0,24.7,33.1,0.0,2.9,-0.2,0.0,-59.8,13.7,13.7,NaN,NaN,NaN,NaN,NaN,78.5,2.1,-10.4,NaN,0.8,0.0,-16.5,NaN,75.2,NaN,42.4,NaN,NaN,-50.9,NaN,0.0,NaN,1.7,NaN,16.8,NaN,NaN,0.0,0.0,8.7,NaN,NaN,NaN,NaN,-14.6,0,0,0
3,A,USD,STD,INDL,C,AIR,2023-05-31,1004,AAR CORP,000361105,1750.0,11.0,5,USA,5,2022,NaN,13.5,56.4,42.9,-23.5,56.4,NaN,1097.9,NaN,0.0,32.7,0.0,0.0,-17.8,0.0,32.7,32.7,158.5,NaN,NaN,NaN,NaN,NaN,NaN,1833.1,31.4784,NaN,484.5,1099.1,1099.1,820.0,68.4,81.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.3,0.0,0.0,0.0,272.0,NaN,NaN,12.3,317.9,269.7,NaN,317.9,0.0,0.0,NaN,268.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.8,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.0,279.1,103.3,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,33.1,NaN,13.4,351.5,NaN,NaN,0.0,NaN,NaN,NaN,31.0,18.3,NaN,NaN,1833.1,734.0,0.0,14.5,12.3,9.1,8.4,7.8,52.1,17.6,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.7,NaN,367.9,NaN,636.7,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.1,0.0,-17.8,0.0,13.4,335.0,-5.7,328.2,135.4,NaN,910.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.8,317.8,0.0,33.6,0.0,0.0,0.0,33.6,-33.6,37.1,70.7,0.0,0.0,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.4,147.6,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.2,-2.9,0.0,0.0,-1.0,0.0,86.3,NaN,1591.3,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.7,0.4,NaN,27.9,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.4,179.3,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.8,88.7,NaN,89.8,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.2,89.1,NaN,NaN,NaN,NaN,NaN,NaN,-3.7,-4.7,NaN,NaN,NaN,151.4,179.3,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.2,87.7,33.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.6,NaN,NaN,1990.6,-1.17,-0.03,-0.03,-1.8,-14.3,-0.07,-0.07,-2.4,-3.1,NaN,13.5,NaN,NaN,NaN,NaN,NaN,33.6,NaN,NaN,-2.2,NaN,NaN,NaN,25.9,4.8,0.0,2.9,31.4,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.3,NaN,NaN,8.0,NaN,29.4,NaN,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.3,NaN,103.3,29.5,29.5,NaN,22.9,NaN,172.0,0.0,0.0,27.9,0.0,3.2,-0.1,-1.9,137.7,17.1,17.1,NaN,NaN,NaN,NaN,NaN,89.8,11.1,-20.6,NaN,-5.2,NaN,-138.0,NaN,23.3,NaN,50.1,NaN,NaN,-31.8,NaN,0.0,NaN,0.7,NaN,17.7,NaN,0.0,0.0,0.0,-2.2,34.4,NaN,NaN,NaN,-0.5,0,0,0

In [9]:
def get_columns_by_dtype(df):
    result = {}
    for dtype, cols in df.columns.to_series().groupby(df.dtypes).groups.items():
        result[str(dtype)] = cols.tolist()
    return result

In [11]:
cols_by_type = get_columns_by_dtype(df)
print(cols_by_type)

{'int64': ['gvkey', 'fyr', 'fyrc', 'fyear', 'closest flag', 'after flag include', 'Delist_Flag'], 'float64': ['cik', 'exchg', 'acco', 'acdo', 'aco', 'acodo', 'acominc', 'acox', 'acoxar', 'act', 'aedi', 'aldo', 'ao', 'aocidergl', 'aociother', 'aocipen', 'aocisecgl', 'aodo', 'aox', 'ap', 'apb', 'apc', 'apofs', 'arb', 'arc', 'artfs', 'at', 'bkvlps', 'ca', 'caps', 'ceq', 'ceql', 'ceqt', 'ch', 'che', 'chs', 'cld2', 'cld3', 'cld4', 'cld5', 'clfc', 'clfx', 'clg', 'clis', 'cll', 'cllc', 'clo', 'clrll', 'clt', 'cmp', 'crv', 'crvnli', 'cstk', 'cstkcv', 'dc', 'dclo', 'dcom', 'dcpstk', 'dcs', 'dcvsr', 'dcvsub', 'dcvt', 'dd', 'dd1', 'dd2', 'dd3', 'dd4', 'dd5', 'dfpac', 'dfs', 'dlc', 'dlto', 'dltp', 'dltsub', 'dltt', 'dm', 'dn', 'dpacre', 'dpact', 'dpdc', 'dpltb', 'dpsc', 'dpstb', 'dptb', 'dptc', 'dptic', 'dpvieb', 'drc', 'drci', 'drlt', 'ds', 'dudd', 'dvpa', 'dxd2', 'dxd3', 'dxd4', 'dxd5', 'ea', 'esopct', 'esopdlt', 'esopnr', 'esopr', 'esopt', 'excadj', 'fatb', 'fatc', 'fate', 'fatl', 'fatn', 'fato', 'fatp', 'fdfr', 'fea', 'fel', 'ffs', 'gdwl', 'geqrv', 'govgr', 'iaeq', 'iaeqci', 'iaeqmi', 'iafici', 'iafxi', 'iafxmi', 'iali', 'ialoi', 'ialti', 'iamli', 'iaoi', 'iapli', 'iarei', 'iasci', 'iasmi', 'iassi', 'iasti', 'iatci', 'iati', 'iatmi', 'iaui', 'icapt', 'intan', 'intano', 'invfg', 'invo', 'invofs', 'invreh', 'invrei', 'invres', 'invrm', 'invt', 'invwip', 'ip', 'ipc', 'ipv', 'iseq', 'iseqc', 'iseqm', 'isfi', 'isfxc', 'isfxm', 'islg', 'islgc', 'islgm', 'islt', 'isng', 'isngc', 'isngm', 'isotc', 'isoth', 'isotm', 'issc', 'issm', 'issu', 'ist', 'istc', 'istm', 'isut', 'itcb', 'ivaeq', 'ivao', 'ivgod', 'ivpt', 'ivst', 'lcabg', 'lcacl', 'lcacr', 'lcag', 'lcal', 'lcalt', 'lcam', 'lcao', 'lcast', 'lcat', 'lco', 'lcox', 'lcoxar', 'lcoxdr', 'lct', 'lcuacu', 'lif', 'lifr', 'lloml', 'lloo', 'llot', 'lo', 'loxdr', 'lrv', 'ls', 'lse', 'lt', 'mib', 'mrc1', 'mrc2', 'mrc3', 'mrc4', 'mrc5', 'mrct', 'mrcta', 'msa', 'msvrv', 'mtl', 'np', 'npanl', 'npaore', 'nparl', 'npat', 'ob', 'optprcca', 'optprcex', 'optprcey', 'optprcgr', 'optprcwa', 'ppegt', 'ppenc', 'ppent', 'ppevbb', 'ppeveb', 'prc', 'prodv', 'prvt', 'pstk', 'pstkc', 'pstkl', 'pstkn', 'pstkr', 'pstkrv', 'pvcl', 'pvpl', 'pvt', 'radp', 'ragr', 'rari', 'rati', 'rcl', 'rdp', 're', 'rea', 'reajo', 'recco', 'recd', 'rect', 'recta', 'rectr', 'recub', 'ret', 'reuna', 'reunr', 'rll', 'rlo', 'rlp', 'rlri', 'rlt', 'rpag', 'rvbci', 'rvbpi', 'rvbti', 'rvdo', 'rvdt', 'rveqt', 'rvlrv', 'rvno', 'rvnt', 'rvri', 'rvsi', 'rvti', 'rvtxr', 'rvupi', 'rvutx', 'saa', 'sal', 'sbdc', 'sc', 'sco', 'secu', 'seq', 'seqo', 'srt', 'ssnp', 'stbo', 'stio', 'tdscd', 'tdsce', 'tdslg', 'tdsmm', 'tdsng', 'tdso', 'tdss', 'tdst', 'tlcf', 'transa', 'tsa', 'tso', 'tstk', 'tstkc', 'tstkp', 'txdb', 'txdba', 'txdbca', 'txdbcl', 'txditc', 'txndb', 'txndba', 'txndbl', 'txndbr', 'txp', 'txr', 'uaox', 'uapt', 'ucaps', 'uccons', 'uceq', 'ucustad', 'udcopres', 'udd', 'udmb', 'udolt', 'udpco', 'ui', 'uinvt', 'ulcm', 'ulco', 'unl', 'unnp', 'unnpl', 'uopres', 'upmcstk', 'upmpf', 'upmpfs', 'upmsubp', 'upstk', 'upstkc', 'upstksf', 'urect', 'urectr', 'urevub', 'usubpstk', 'vpac', 'vpo', 'wcap', 'xacc', 'xpp', 'acchg', 'adpac', 'am', 'amdc', 'amgw', 'aqa', 'aqd', 'aqeps', 'aqi', 'aqp', 'aqs', 'autxr', 'balr', 'banlr', 'batr', 'bcef', 'bclr', 'bcltbl', 'bcnlr', 'bcrbl', 'bct', 'bctbl', 'bctr', 'bltbl', 'cbi', 'cdpac', 'cfbd', 'cfere', 'cfo', 'cfpdo', 'cga', 'cgri', 'cgti', 'cgui', 'cibegni', 'cicurr', 'cidergl', 'ciother', 'cipen', 'cisecgl', 'citotal', 'cnltbl', 'cogs', 'cpcbl', 'cpdoi', 'cpnli', 'cppbl', 'cprei', 'cstke', 'dbi', 'dfxa', 'diladj', 'dilavx', 'do', 'donr', 'dp', 'dpret', 'dtea', 'dted', 'dteeps', 'dtep', 'dvc', 'dvdnp', 'dvp', 'dvpd', 'dvpdp', 'dvrpiv', 'dvrre', 'dvsco', 'dvt', 'ebit', 'ebitda', 'eiea', 'emol', 'epsfi', 'epsfx', 'epspi', 'epspx', 'esub', 'fatd', 'fca', 'ffo', 'gbbl', 'gdwlia', 'gdwlid', 'gdwlieps', 'gdwlip', 'gla', 'glcea', 'glced', 'glceeps', 'glcep', 'gld', 'gleps', 'glp', 'gp', 'gphbl', 'gplbl', 'gpobl', 'gprbl', 'gptbl', 'gwo', 'hedgegl', 'ib', 'ibadj', 'ibbl', 'ibcom', 'ibki', 'idiis', 'idilb', 'idilc', 'idis', 'idist', 'idit', 'idits', 'iire', 'initb', 'intc', 'iobd', 'ioi', 'iore', 'ipabl', 'iphbl', 'iplbl', 'ipobl', 'iptbl', 'ipti', 'irei', 'irent', 'irii', 'irli', 'irnli', 'irsi', 'isgr', 'isgt', 'isgu', 'itci', 'ivi', 'li', 'llrci', 'llrcr', 'llwoci', 'llwocr', 'lst', 'mii', 'nco', 'nfsr', 'ni', 'niadj', 'niint', 'niit', 'nim', 'nio', 'nit', 'nits', 'nopi', 'nopio', 'nrtxt', 'nrtxtd', 'nrtxteps', 'oiadp', 'oibdp', 'opeps', 'opili', 'opincar', 'opini', 'opioi', 'opiri', 'opiti', 'oprepsx', 'palr', 'panlr', 'patr', 'pcl', 'pclr', 'pcnlr', 'pctr', 'pi', 'pidom', 'pifo', 'pll', 'pltbl', 'pnca', 'pncad', 'pncaeps', 'pnlbl', 'pnli', 'pobl', 'ppcbl', 'pppabl', 'ppphbl', 'pppobl', 'ppptbl', 'prca', 'prcad', 'prcaeps', 'prebl', 'pri', 'ptbl', 'ptran', 'pvo', 'pvon', 'pwoi', 'rca', 'rcd', 'rceps', 'rcp', 'rdip', 'rdipa', 'rdipd', 'rdipeps', 'revt', 'ris', 'rmum', 'sale', 'seta', 'setd', 'seteps', 'setp', 'spi', 'spid', 'spieps', 'spioa', 'spiop', 'sret', 'stkco', 'stkcpa', 'tdsg', 'tf', 'tie', 'tii', 'txc', 'txdfed', 'txdfo', 'txdi', 'txds', 'txeqa', 'txeqii', 'txfed', 'txfo', 'txo', 'txs', 'txt', 'txva', 'txw', 'udpfa', 'udvp', 'ugi', 'uniami', 'unopinc', 'uopi', 'updvp', 'uspi', 'usubdvp', 'utme', 'utxfed', 'uxinst', 'uxintd', 'wda', 'wdd', 'wdeps', 'wdp', 'xad', 'xago', 'xagt', 'xcom', 'xcomi', 'xdvre', 'xeqo', 'xi', 'xido', 'xindb', 'xindc', 'xins', 'xinst', 'xint', 'xintd', 'xivi', 'xivre', 'xlr', 'xnbi', 'xnf', 'xnins', 'xnitb', 'xobd', 'xoi', 'xopr', 'xoprar', 'xore', 'xpr', 'xrd', 'xrent', 'xs', 'xsga', 'xstf', 'xstfo', 'xstfws', 'xt', 'xuw', 'xuwli', 'xuwnli', 'xuwoi', 'xuwrei', 'xuwti', 'afudcc', 'afudci', 'amc', 'aoloch', 'apalch', 'aqc', 'capx', 'capxv', 'cdvc', 'chech', 'depc', 'dlcch', 'dltis', 'dltr', 'dpc', 'dv', 'esubc', 'exre', 'fiao', 'fincf', 'fopo', 'fopox', 'fopt', 'fsrco', 'fsrct', 'fuseo', 'fuset', 'ibc', 'intpn', 'invch', 'itcc', 'ivaco', 'ivch', 'ivncf', 'ivstch', 'oancf', 'pdvc', 'prstkc', 'prstkcc', 'prstkpc', 'recch', 'scstkc', 'siv', 'sppe', 'sppiv', 'spstkc', 'sstk', 'tdc', 'txach', 'txbco', 'txbcof', 'txdc', 'txpd', 'uaoloch', 'udfcc', 'uois', 'xidoc'], 'object': ['costat', 'curcd', 'datafmt', 'indfmt', 'consol', 'tic', 'datadate', 'conm', 'cusip', 'fic']}

In [13]:
#df中為object的欄位
df[['costat', 'curcd', 'datafmt', 'indfmt', 'consol', 'tic', 'datadate', 'conm', 'cusip', 'fic']]

,costat,curcd,datafmt,indfmt,consol,tic,datadate,conm,cusip,fic
0,A,USD,STD,INDL,C,AIR,2020-05-31,AAR CORP,000361105,USA
1,A,USD,STD,INDL,C,AIR,2021-05-31,AAR CORP,000361105,USA
2,A,USD,STD,INDL,C,AIR,2022-05-31,AAR CORP,000361105,USA
3,A,USD,STD,INDL,C,AIR,2023-05-31,AAR CORP,000361105,USA
4,A,USD,STD,INDL,C,AIR,2024-05-31,AAR CORP,000361105,USA
...,...,...,...,...,...,...,...,...,...,...
56087,A,USD,STD,INDL,C,INDP,2024-12-31,INDAPTUS THERAPEUTICS INC,45339J204,USA
56088,A,USD,STD,INDL,C,BEMB,2023-12-31,ISHARES JP MORGAN B U E M B,46436E262,USA
56089,A,USD,STD,INDL,C,BEMB,2024-12-31,ISHARES JP MORGAN B U E M B,46436E262,USA
56090,A,USD,STD,INDL,C,TIC,2023-12-31,ACUREN CORP,00510N102,USA
56091,A,USD,STD,INDL,C,TIC,2024-12-31,ACUREN CORP,00510N102,USA

In [15]:
# 計算每個欄位的不同值數量
n_unique = df[['costat', 'curcd', 'datafmt', 'indfmt', 'consol', 'tic', 'datadate', 'conm', 'cusip', 'fic']].nunique()

# 找出只有一個值的欄位
cols_with_one_value = n_unique[n_unique == 1].index.tolist()

print("欄位只有一個值的有：", cols_with_one_value)

欄位只有一個值的有： ['curcd', 'datafmt', 'consol', 'fic']

In [17]:
#刪掉只有一個值的欄位
data_d=df.drop(['curcd', 'datafmt', 'consol', 'fic'],axis=1)

In [21]:
#剩下的欄位 另加入'fyear'欄位觀察和 datadate的關係
data_d[['costat', 'indfmt', 'tic', 'datadate', 'conm', 'cusip','fyear']]

,costat,indfmt,tic,datadate,conm,cusip,fyear
0,A,INDL,AIR,2020-05-31,AAR CORP,000361105,2019
1,A,INDL,AIR,2021-05-31,AAR CORP,000361105,2020
2,A,INDL,AIR,2022-05-31,AAR CORP,000361105,2021
3,A,INDL,AIR,2023-05-31,AAR CORP,000361105,2022
4,A,INDL,AIR,2024-05-31,AAR CORP,000361105,2023
...,...,...,...,...,...,...,...
56087,A,INDL,INDP,2024-12-31,INDAPTUS THERAPEUTICS INC,45339J204,2024
56088,A,INDL,BEMB,2023-12-31,ISHARES JP MORGAN B U E M B,46436E262,2023
56089,A,INDL,BEMB,2024-12-31,ISHARES JP MORGAN B U E M B,46436E262,2024
56090,A,INDL,TIC,2023-12-31,ACUREN CORP,00510N102,2023
56091,A,INDL,TIC,2024-12-31,ACUREN CORP,00510N102,2024

In [23]:
data_dd=data_d.drop(['cusip', 'datadate'],axis=1) #日期欄位不能跑模型

In [25]:
data_dd[['costat', 'indfmt', 'tic', 'conm']] #'costat', 'indfmt'行業, 'tic'股票代稱, 'conm'公司名稱

      costat indfmt   tic                         conm
0          A   INDL   AIR                     AAR CORP
1          A   INDL   AIR                     AAR CORP
2          A   INDL   AIR                     AAR CORP
3          A   INDL   AIR                     AAR CORP
4          A   INDL   AIR                     AAR CORP
...      ...    ...   ...                          ...
56087      A   INDL  INDP    INDAPTUS THERAPEUTICS INC
56088      A   INDL  BEMB  ISHARES JP MORGAN B U E M B
56089      A   INDL  BEMB  ISHARES JP MORGAN B U E M B
56090      A   INDL   TIC                  ACUREN CORP
56091      A   INDL   TIC                  ACUREN CORP

[56092 rows x 4 columns]

In [27]:
# 計算每個欄位的不同值個數
distinct_counts = data_dd[['costat', 'indfmt', 'tic', 'conm', 'cik', 'exchg','gvkey']].nunique()
# 顯示結果
print(distinct_counts)

costat        2
indfmt        2
tic       11431
conm      11431
cik        6648
exchg        10
gvkey     11431
dtype: int64

In [29]:
data_ddd=data_dd.drop(['tic', 'conm','cik','fyr','fyrc'],axis=1) #cik=就像是公司在SEC系統中的身份證號碼

In [31]:
data_ddd.shape

(56092, 728)

In [33]:
data_ddd.iloc[:, :728].head()

,costat,indfmt,gvkey,exchg,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc,closest flag,after flag include,Delist_Flag
0,A,INDL,1004,11.0,2019,NaN,22.9,92.2,69.3,-44.6,92.2,NaN,1438.7,NaN,0.0,37.2,0.0,0.0,-42.6,0.0,37.2,37.2,191.6,NaN,NaN,NaN,NaN,NaN,NaN,2079.0,25.7173,NaN,478.6,902.6,902.6,776.8,404.7,424.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.7,22.5,0.0,0.0,579.5,NaN,NaN,13.7,672.9,600.0,NaN,670.9,0.0,0.0,NaN,246.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.5,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.5,125.8,10.1,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.8,41.1,NaN,29.9,383.1,NaN,NaN,0.0,NaN,NaN,NaN,122.4,34.4,NaN,NaN,2079.0,1176.4,0.0,16.5,14.5,12.7,10.7,8.3,62.7,36.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.6,NaN,437.1,NaN,683.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.4,0.0,-42.6,0.0,22.1,229.1,-2.0,221.2,49.3,NaN,706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.7,282.7,0.0,0.0,3.5,0.0,0.0,0.0,3.5,64.9,61.4,0.0,0.0,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.6,136.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.4,0.1,0.0,0.0,-3.8,0.0,0.7,NaN,1728.7,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.7,-20.4,NaN,43.7,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.4,150.1,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.8,24.7,NaN,24.8,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.4,4.3,NaN,NaN,NaN,NaN,NaN,NaN,-3.5,-4.0,NaN,NaN,NaN,106.4,150.1,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.4,23.6,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.3,NaN,NaN,2089.3,NaN,NaN,NaN,NaN,-63.2,-0.20,-0.20,-6.8,-8.9,NaN,7.3,NaN,NaN,NaN,NaN,NaN,5.1,NaN,NaN,0.5,NaN,NaN,NaN,1.4,2.8,0.0,0.9,5.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.2,NaN,NaN,14.9,NaN,31.1,NaN,210.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,0.0,23.6,23.6,NaN,383.6,NaN,459.5,0.0,0.0,43.7,10.7,1.9,0.0,-1.3,444.5,52.1,52.1,NaN,NaN,NaN,NaN,NaN,24.8,8.6,-98.8,NaN,-1.2,0.0,-24.8,NaN,-36.1,NaN,4.1,NaN,NaN,24.7,NaN,0.0,NaN,0.0,NaN,1.1,NaN,0.0,0.0,0.0,0.5,NaN,NaN,NaN,NaN,-17.0,0,0,0
1,A,INDL,1004,11.0,2020,NaN,19.5,47.2,27.7,-18.3,47.2,NaN,937.0,NaN,0.0,33.9,0.0,0.0,-22.2,0.0,33.9,33.9,127.2,NaN,NaN,NaN,NaN,NaN,NaN,1539.7,27.5449,NaN,479.8,974.4,974.4,825.6,51.8,60.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.5,0.0,0.0,109.5,0.0,NaN,NaN,11.5,195.1,133.7,NaN,193.6,0.0,0.0,NaN,260.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.2,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.0,148.8,29.5,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.4,61.3,NaN,35.4,336.8,NaN,NaN,0.0,NaN,NaN,NaN,25.4,20.0,NaN,NaN,1539.7,565.3,0.0,13.7,11.9,9.9,8.8,7.7,52.0,32.9,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.3,NaN,380.1,NaN,640.3,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.4,0.0,-22.2,0.0,16.4,238.6,3.9,238.6,71.9,NaN,741.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.1,274.1,0.0,9.5,0.0,0.0,0.0,9.5,-9.5,44.5,54.0,0.0,0.7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.2,136.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.8,5.9,0.0,0.0,20.4,0.0,62.1,NaN,1364.6,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.9,-10.5,NaN,36.3,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.5,101.8,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,45.9,NaN,46.3,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.8,35.4,NaN,NaN,NaN,NaN,NaN,NaN,-12.1,-12.3,NaN,NaN,NaN,65.5,101.8,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.5,43.7,20.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.4,NaN,NaN,1651.4,3.30,0.09,0.09,4.3,16.1,0.82,0.82,28.6,37.6,NaN,9.2,NaN,NaN,NaN,NaN,NaN,9.8,NaN,NaN,8.4,NaN,NaN,NaN,5.2,3.4,0.0,1.2,18.2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.6,NaN,NaN,6.2,NaN,21.6,NaN,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.5,NaN,0.0,11.3,11.3,NaN,-364.5,NaN,-470.0,0.0,0.0,36.3,0.1,-0.2,0.3,0.0,-469.5,29.0,29.0,NaN,NaN,NaN,NaN,NaN,46.3,4.3,74.9,NaN,10.8,0.0,-0.5,NaN,105.2,NaN,0.0,NaN,NaN,-30.9,NaN,0.0,0.0,20.2,NaN,0.6,NaN,NaN,0.0,0.0,8.4,NaN,NaN,NaN,NaN,-3.3,0,0,0
2,A,INDL,1004,11.0,2021,NaN,16.2,53.9,37.7,-19.6,53.9,NaN,1007.2,NaN,0.0,33.1,0.0,0.0,-16.8,0.0,33.1,33.1,156.4,NaN,NaN,NaN,NaN,NaN,NaN,1573.9,29.2306,NaN,477.5,1034.5,1034.5,892.6,53.5,58.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.1,0.0,100.0,0.0,0.0,NaN,NaN,11.1,157.4,98.9,NaN,156.3,0.0,0.0,NaN,258.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.3,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.8,141.9,25.5,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,37.7,NaN,17.2,348.2,NaN,NaN,0.0,NaN,NaN,NaN,14.9,4.8,NaN,NaN,1573.9,539.4,0.0,13.6,12.4,11.0,9.2,8.5,54.7,25.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.5,NaN,349.2,NaN,607.5,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.8,0.0,-16.8,0.0,17.9,290.3,-2.8,287.6,119.2,NaN,820.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.1,289.1,0.0,20.0,0.0,0.0,0.0,20.0,-20.0,38.5,58.5,0.0,0.0,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.0,143.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.7,-6.7,0.0,0.0,5.4,0.0,77.4,NaN,1470.3,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.9,0.2,NaN,33.1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.2,149.3,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.5,77.9,NaN,78.5,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.7,78.1,NaN,NaN,NaN,NaN,NaN,NaN,-2.3,-2.4,NaN,NaN,NaN,116.2,149.3,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.1,77.1,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.1,NaN,NaN,1817.1,NaN,NaN,NaN,NaN,-6.4,0.01,0.01,0.3,0.2,NaN,8.2,NaN,NaN,NaN,NaN,NaN,17.9,NaN,NaN,8.7,NaN,NaN,NaN,11.0,4.3,0.0,2.6,26.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.8,NaN,NaN,7.3,NaN,32.2,NaN,197.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,NaN,0.0,17.3,17.3,NaN,-1.3,NaN,-9.5,0.0,24.7,33.1,0.0,2.9,-0.2,0.0,-59.8,13.7,13.7,NaN,NaN,NaN,NaN,NaN,78.5,2.1,-10.4,NaN,0.8,0.0,-16.5,NaN,75.2,NaN,42.4,NaN,NaN,-50.9,NaN,0.0,NaN,1.7,NaN,16.8,NaN,NaN,0.0,0.0,8.7,NaN,NaN,NaN,NaN,-14.6,0,0,0
3,A,INDL,1004,11.0,2022,NaN,13.5,56.4,42.9,-23.5,56.4,NaN,1097.9,NaN,0.0,32.7,0.0,0.0,-17.8,0.0,32.7,32.7,158.5,NaN,NaN,NaN,NaN,NaN,NaN,1833.1,31.4784,NaN,484.5,1099.1,1099.1,820.0,68.4,81.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.3,0.0,0.0,0.0,272.0,NaN,NaN,12.3,317.9,269.7,NaN,317.9,0.0,0.0,NaN,268.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.8,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.0,279.1,103.3,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,33.1,NaN,13.4,351.5,NaN,NaN,0.0,NaN,NaN,NaN,31.0,18.3,NaN,NaN,1833.1,734.0,0.0,14.5,12.3,9.1,8.4,7.8,52.1,17.6,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.7,NaN,367.9,NaN,636.7,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.1,0.0,-17.8,0.0,13.4,335.0,-5.7,328.2,135.4,NaN,910.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.8,317.8,0.0,33.6,0.0,0.0,0.0,33.6,-33.6,37.1,70.7,0.0,0.0,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.4,147.6,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.2,-2.9,0.0,0.0,-1.0,0.0,86.3,NaN,1591.3,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.7,0.4,NaN,27.9,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.4,179.3,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.8,88.7,NaN,89.8,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.2,89.1,NaN,NaN,NaN,NaN,NaN,NaN,-3.7,-4.7,NaN,NaN,NaN,151.4,179.3,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.2,87.7,33.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.6,NaN,NaN,1990.6,-1.17,-0.03,-0.03,-1.8,-14.3,-0.07,-0.07,-2.4,-3.1,NaN,13.5,NaN,NaN,NaN,NaN,NaN,33.6,NaN,NaN,-2.2,NaN,NaN,NaN,25.9,4.8,0.0,2.9,31.4,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.3,NaN,NaN,8.0,NaN,29.4,NaN,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.3,NaN,103.3,29.5,29.5,NaN,22.9,NaN,172.0,0.0,0.0,27.9,0.0,3.2,-0.1,-1.9,137.7,17.1,17.1,NaN,NaN,NaN,NaN,NaN,89.8,11.1,-20.6,NaN,-5.2,NaN,-138.0,NaN,23.3,NaN,50.1,NaN,NaN,-31.8,NaN,0.0,NaN,0.7,NaN,17.7,NaN,0.0,0.0,0.0,-2.2,34.4,NaN,NaN,NaN,-0.5,0,0,0
4,A,INDL,1004,11.0,2023,NaN,9.9,55.3,45.4,-8.8,55.3,NaN,1389.6,NaN,0.0,29.0,0.0,0.0,-3.3,0.0,29.0,29.0,238.0,NaN,NaN,NaN,NaN,NaN,NaN,2770.0,33.3333,NaN,493.9,1189.8,1189.8,347.8,85.8,96.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.2,0.0,0.0,447.0,550.0,NaN,NaN,13.2,527.3,447.0,NaN,1065.7,0.0,550.0,NaN,280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280.0,14.7,NaN,7.2,0.0,-11.6,0.0,0.0,0.0,447.0,550.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,554.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2255.5,842.0,287.2,NaN,NaN,NaN,NaN,NaN,NaN,114.1,814.6,38.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,35.8,39.0,NaN,NaN,10.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.7,24.3,NaN,9.6,466.9,NaN,NaN,0.0,NaN,NaN,NaN,23.7,16.5,NaN,NaN,2770.0,1580.2,0.0,16.7,12.8,10.8,9.8,7.4,57.5,88.8,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,668.0,48.40,30.67,38.49,58.27,33.95,714.6,NaN,434.6,NaN,714.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,948.1,0.0,-3.3,0.0,14.1,423.6,-5.5,410.4,159.9,NaN,956.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.5,297.5,0.0,23.9,0.0,0.0,0.0,23.9,-23.9,47.7,71.6,0.0,0.0,13.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,922.7,191.4,NaN,0.0,NaN,NaN,NaN,NaN,-19.305,-0.55,-0.55,NaN,-29.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,0.2,0.0,0.0,14.5,0.0,61.0,NaN,1835.4,NaN,NaN,NaN,NaN,NaN,-0.5,NaN,NaN,0.0,45.8,0.0,0.0,41.2,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,174.4,215.6,NaN,NaN,1.29,1.29,1.30,1.30,-0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,485.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,45.8,NaN,46.3,NaN,NaN,NaN,NaN,NaN,NaN,2.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,46.3,45.8,NaN,NaN,NaN,NaN,NaN,NaN,-1.2,-3.4,NaN,NaN,NaN,174.4,215.6,3.04,NaN,NaN,NaN,NaN,NaN,NaN,3.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.3,14.6,43.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.325,-0.01,-0.01,-0.5,0.0,0.0,0.0,0.0,2321.2,NaN,NaN,2321.2,-7.28,-0.21,-0.21,-11.2,-71.7,-0.77,-0.78,-27.3,-42.0,NaN,15.3,NaN,NaN,NaN,NaN,NaN,32.5,NaN,NaN,-20.5,NaN,NaN,NaN,21.0,7.5,0.0,4.0,12.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,43.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2105.6,NaN,NaN,9.5,NaN,35.9,NaN,270.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.9,NaN,722.9,29.7,29.7,NaN,14.3,NaN,175.0,550.0,0.0,41.2,0.0,0.2,0.0,-10.3,729.2,42.7,42.7,NaN,NaN,NaN,NaN,NaN,46.3,31.9,-101.6,NaN,-5.9,NaN,-758.5,NaN,43.6,NaN,5.1,NaN,NaN,-22.4,NaN,0.0,0.0,0.0,NaN,19.6,NaN,0.0,0.0,0.0,-20.5,41.8,NaN,NaN,NaN,-0.2,0,0,0

In [35]:
#先跑一次沒有one hot encoding的dataset (刪除非有意義的數值欄位和非數值欄位）
data_ddd.iloc[:, 4:728].head()

,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc,closest flag,after flag include,Delist_Flag
0,2019,NaN,22.9,92.2,69.3,-44.6,92.2,NaN,1438.7,NaN,0.0,37.2,0.0,0.0,-42.6,0.0,37.2,37.2,191.6,NaN,NaN,NaN,NaN,NaN,NaN,2079.0,25.7173,NaN,478.6,902.6,902.6,776.8,404.7,424.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.7,22.5,0.0,0.0,579.5,NaN,NaN,13.7,672.9,600.0,NaN,670.9,0.0,0.0,NaN,246.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.5,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.5,125.8,10.1,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.8,41.1,NaN,29.9,383.1,NaN,NaN,0.0,NaN,NaN,NaN,122.4,34.4,NaN,NaN,2079.0,1176.4,0.0,16.5,14.5,12.7,10.7,8.3,62.7,36.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.6,NaN,437.1,NaN,683.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.4,0.0,-42.6,0.0,22.1,229.1,-2.0,221.2,49.3,NaN,706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.7,282.7,0.0,0.0,3.5,0.0,0.0,0.0,3.5,64.9,61.4,0.0,0.0,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.6,136.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.4,0.1,0.0,0.0,-3.8,0.0,0.7,NaN,1728.7,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.7,-20.4,NaN,43.7,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.4,150.1,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.8,24.7,NaN,24.8,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.4,4.3,NaN,NaN,NaN,NaN,NaN,NaN,-3.5,-4.0,NaN,NaN,NaN,106.4,150.1,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.4,23.6,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.3,NaN,NaN,2089.3,NaN,NaN,NaN,NaN,-63.2,-0.20,-0.20,-6.8,-8.9,NaN,7.3,NaN,NaN,NaN,NaN,NaN,5.1,NaN,NaN,0.5,NaN,NaN,NaN,1.4,2.8,0.0,0.9,5.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.2,NaN,NaN,14.9,NaN,31.1,NaN,210.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,0.0,23.6,23.6,NaN,383.6,NaN,459.5,0.0,0.0,43.7,10.7,1.9,0.0,-1.3,444.5,52.1,52.1,NaN,NaN,NaN,NaN,NaN,24.8,8.6,-98.8,NaN,-1.2,0.0,-24.8,NaN,-36.1,NaN,4.1,NaN,NaN,24.7,NaN,0.0,NaN,0.0,NaN,1.1,NaN,0.0,0.0,0.0,0.5,NaN,NaN,NaN,NaN,-17.0,0,0,0
1,2020,NaN,19.5,47.2,27.7,-18.3,47.2,NaN,937.0,NaN,0.0,33.9,0.0,0.0,-22.2,0.0,33.9,33.9,127.2,NaN,NaN,NaN,NaN,NaN,NaN,1539.7,27.5449,NaN,479.8,974.4,974.4,825.6,51.8,60.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.5,0.0,0.0,109.5,0.0,NaN,NaN,11.5,195.1,133.7,NaN,193.6,0.0,0.0,NaN,260.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.2,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.0,148.8,29.5,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.4,61.3,NaN,35.4,336.8,NaN,NaN,0.0,NaN,NaN,NaN,25.4,20.0,NaN,NaN,1539.7,565.3,0.0,13.7,11.9,9.9,8.8,7.7,52.0,32.9,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.3,NaN,380.1,NaN,640.3,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.4,0.0,-22.2,0.0,16.4,238.6,3.9,238.6,71.9,NaN,741.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.1,274.1,0.0,9.5,0.0,0.0,0.0,9.5,-9.5,44.5,54.0,0.0,0.7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.2,136.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.8,5.9,0.0,0.0,20.4,0.0,62.1,NaN,1364.6,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.9,-10.5,NaN,36.3,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.5,101.8,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,45.9,NaN,46.3,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.8,35.4,NaN,NaN,NaN,NaN,NaN,NaN,-12.1,-12.3,NaN,NaN,NaN,65.5,101.8,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.5,43.7,20.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.4,NaN,NaN,1651.4,3.30,0.09,0.09,4.3,16.1,0.82,0.82,28.6,37.6,NaN,9.2,NaN,NaN,NaN,NaN,NaN,9.8,NaN,NaN,8.4,NaN,NaN,NaN,5.2,3.4,0.0,1.2,18.2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.6,NaN,NaN,6.2,NaN,21.6,NaN,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.5,NaN,0.0,11.3,11.3,NaN,-364.5,NaN,-470.0,0.0,0.0,36.3,0.1,-0.2,0.3,0.0,-469.5,29.0,29.0,NaN,NaN,NaN,NaN,NaN,46.3,4.3,74.9,NaN,10.8,0.0,-0.5,NaN,105.2,NaN,0.0,NaN,NaN,-30.9,NaN,0.0,0.0,20.2,NaN,0.6,NaN,NaN,0.0,0.0,8.4,NaN,NaN,NaN,NaN,-3.3,0,0,0
2,2021,NaN,16.2,53.9,37.7,-19.6,53.9,NaN,1007.2,NaN,0.0,33.1,0.0,0.0,-16.8,0.0,33.1,33.1,156.4,NaN,NaN,NaN,NaN,NaN,NaN,1573.9,29.2306,NaN,477.5,1034.5,1034.5,892.6,53.5,58.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.1,0.0,100.0,0.0,0.0,NaN,NaN,11.1,157.4,98.9,NaN,156.3,0.0,0.0,NaN,258.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.3,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.8,141.9,25.5,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,37.7,NaN,17.2,348.2,NaN,NaN,0.0,NaN,NaN,NaN,14.9,4.8,NaN,NaN,1573.9,539.4,0.0,13.6,12.4,11.0,9.2,8.5,54.7,25.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.5,NaN,349.2,NaN,607.5,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.8,0.0,-16.8,0.0,17.9,290.3,-2.8,287.6,119.2,NaN,820.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.1,289.1,0.0,20.0,0.0,0.0,0.0,20.0,-20.0,38.5,58.5,0.0,0.0,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.0,143.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.7,-6.7,0.0,0.0,5.4,0.0,77.4,NaN,1470.3,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.9,0.2,NaN,33.1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.2,149.3,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.5,77.9,NaN,78.5,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.7,78.1,NaN,NaN,NaN,NaN,NaN,NaN,-2.3,-2.4,NaN,NaN,NaN,116.2,149.3,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.1,77.1,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.1,NaN,NaN,1817.1,NaN,NaN,NaN,NaN,-6.4,0.01,0.01,0.3,0.2,NaN,8.2,NaN,NaN,NaN,NaN,NaN,17.9,NaN,NaN,8.7,NaN,NaN,NaN,11.0,4.3,0.0,2.6,26.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.8,NaN,NaN,7.3,NaN,32.2,NaN,197.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,NaN,0.0,17.3,17.3,NaN,-1.3,NaN,-9.5,0.0,24.7,33.1,0.0,2.9,-0.2,0.0,-59.8,13.7,13.7,NaN,NaN,NaN,NaN,NaN,78.5,2.1,-10.4,NaN,0.8,0.0,-16.5,NaN,75.2,NaN,42.4,NaN,NaN,-50.9,NaN,0.0,NaN,1.7,NaN,16.8,NaN,NaN,0.0,0.0,8.7,NaN,NaN,NaN,NaN,-14.6,0,0,0
3,2022,NaN,13.5,56.4,42.9,-23.5,56.4,NaN,1097.9,NaN,0.0,32.7,0.0,0.0,-17.8,0.0,32.7,32.7,158.5,NaN,NaN,NaN,NaN,NaN,NaN,1833.1,31.4784,NaN,484.5,1099.1,1099.1,820.0,68.4,81.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.3,0.0,0.0,0.0,272.0,NaN,NaN,12.3,317.9,269.7,NaN,317.9,0.0,0.0,NaN,268.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.8,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.0,279.1,103.3,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.7,33.1,NaN,13.4,351.5,NaN,NaN,0.0,NaN,NaN,NaN,31.0,18.3,NaN,NaN,1833.1,734.0,0.0,14.5,12.3,9.1,8.4,7.8,52.1,17.6,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.7,NaN,367.9,NaN,636.7,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.1,0.0,-17.8,0.0,13.4,335.0,-5.7,328.2,135.4,NaN,910.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.8,317.8,0.0,33.6,0.0,0.0,0.0,33.6,-33.6,37.1,70.7,0.0,0.0,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.4,147.6,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.2,-2.9,0.0,0.0,-1.0,0.0,86.3,NaN,1591.3,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.7,0.4,NaN,27.9,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.4,179.3,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.8,88.7,NaN,89.8,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.2,89.1,NaN,NaN,NaN,NaN,NaN,NaN,-3.7,-4.7,NaN,NaN,NaN,151.4,179.3,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.2,87.7,33.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.6,NaN,NaN,1990.6,-1.17,-0.03,-0.03,-1.8,-14.3,-0.07,-0.07,-2.4,-3.1,NaN,13.5,NaN,NaN,NaN,NaN,NaN,33.6,NaN,NaN,-2.2,NaN,NaN,NaN,25.9,4.8,0.0,2.9,31.4,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.3,NaN,NaN,8.0,NaN,29.4,NaN,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.3,NaN,103.3,29.5,29.5,NaN,22.9,NaN,172.0,0.0,0.0,27.9,0.0,3.2,-0.1,-1.9,137.7,17.1,17.1,NaN,NaN,NaN,NaN,NaN,89.8,11.1,-20.6,NaN,-5.2,NaN,-138.0,NaN,23.3,NaN,50.1,NaN,NaN,-31.8,NaN,0.0,NaN,0.7,NaN,17.7,NaN,0.0,0.0,0.0,-2.2,34.4,NaN,NaN,NaN,-0.5,0,0,0
4,2023,NaN,9.9,55.3,45.4,-8.8,55.3,NaN,1389.6,NaN,0.0,29.0,0.0,0.0,-3.3,0.0,29.0,29.0,238.0,NaN,NaN,NaN,NaN,NaN,NaN,2770.0,33.3333,NaN,493.9,1189.8,1189.8,347.8,85.8,96.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.2,0.0,0.0,447.0,550.0,NaN,NaN,13.2,527.3,447.0,NaN,1065.7,0.0,550.0,NaN,280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280.0,14.7,NaN,7.2,0.0,-11.6,0.0,0.0,0.0,447.0,550.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,554.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2255.5,842.0,287.2,NaN,NaN,NaN,NaN,NaN,NaN,114.1,814.6,38.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,35.8,39.0,NaN,NaN,10.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.7,24.3,NaN,9.6,466.9,NaN,NaN,0.0,NaN,NaN,NaN,23.7,16.5,NaN,NaN,2770.0,1580.2,0.0,16.7,12.8,10.8,9.8,7.4,57.5,88.8,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,668.0,48.40,30.67,38.49,58.27,33.95,714.6,NaN,434.6,NaN,714.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,948.1,0.0,-3.3,0.0,14.1,423.6,-5.5,410.4,159.9,NaN,956.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.5,297.5,0.0,23.9,0.0,0.0,0.0,23.9,-23.9,47.7,71.6,0.0,0.0,13.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,922.7,191.4,NaN,0.0,NaN,NaN,NaN,NaN,-19.305,-0.55,-0.55,NaN,-29.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,0.2,0.0,0.0,14.5,0.0,61.0,NaN,1835.4,NaN,NaN,NaN,NaN,NaN,-0.5,NaN,NaN,0.0,45.8,0.0,0.0,41.2,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,174.4,215.6,NaN,NaN,1.29,1.29,1.30,1.30,-0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,485.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.3,45.8,NaN,46.3,NaN,NaN,NaN,NaN,NaN,NaN,2.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,46.3,45.8,NaN,NaN,NaN,NaN,NaN,NaN,-1.2,-3.4,NaN,NaN,NaN,174.4,215.6,3.04,NaN,NaN,NaN,NaN,NaN,NaN,3.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.3,14.6,43.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.325,-0.01,-0.01,-0.5,0.0,0.0,0.0,0.0,2321.2,NaN,NaN,2321.2,-7.28,-0.21,-0.21,-11.2,-71.7,-0.77,-0.78,-27.3,-42.0,NaN,15.3,NaN,NaN,NaN,NaN,NaN,32.5,NaN,NaN,-20.5,NaN,NaN,NaN,21.0,7.5,0.0,4.0,12.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,43.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2105.6,NaN,NaN,9.5,NaN,35.9,NaN,270.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.9,NaN,722.9,29.7,29.7,NaN,14.3,NaN,175.0,550.0,0.0,41.2,0.0,0.2,0.0,-10.3,729.2,42.7,42.7,NaN,NaN,NaN,NaN,NaN,46.3,31.9,-101.6,NaN,-5.9,NaN,-758.5,NaN,43.6,NaN,5.1,NaN,NaN,-22.4,NaN,0.0,0.0,0.0,NaN,19.6,NaN,0.0,0.0,0.0,-20.5,41.8,NaN,NaN,NaN,-0.2,0,0,0

In [200]:
data_ddd.shape

(56092, 728)

In [75]:
# 如果你只需要最接近的行（flag=1），可以篩選
flag_rows = data_ddd[data_ddd['closest flag'] == 1].copy()
flag_rows.shape

(64, 728)

In [77]:
#closest flag
flag_rows_2024 = flag_rows[flag_rows['fyear'] == 2024].copy()
flag_rows_2024.shape

(2, 728)

In [71]:
# 如果你只需要最接近的行（flag=1），可以篩選
flag_rows = data_ddd[data_ddd['after flag include'] == 1].copy()
flag_rows.shape

(107, 728)

In [73]:
#after flag include
flag_rows_2024 = flag_rows[flag_rows['fyear'] == 2024].copy()
flag_rows_2024.shape

(9, 728)

In [67]:
# 如果你只需要最接近的行（flag=1），可以篩選
flag_rows = data_ddd[data_ddd['Delist_Flag'] == 1].copy()
flag_rows.shape

(217, 728)

In [69]:
#Delist_Flag
flag_rows_2024 = flag_rows[flag_rows['fyear'] == 2024].copy()
flag_rows_2024.shape

(9, 728)

沒有one-hot encoding + 用"平均值"補 missing value

## 1)y = data_ddd['closest flag'] ##

In [37]:
# 按時間分測試集2024和訓練集2019-2023
X = data_ddd.iloc[:, 4:725]  # 特徵欄位
y = data_ddd['closest flag']

# 根據年代分割
X_train = X[data_ddd['fyear'].between(2019, 2023)]
y_train = y[data_ddd['fyear'].between(2019, 2023)]

X_test = X[data_ddd['fyear'] == 2024]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape, "測試集大小:", X_test.shape)

訓練集大小: (46854, 721) 測試集大小: (9238, 721)

In [49]:
y_test

(9238,)

In [39]:
# 建立模型
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)

In [41]:
#用"平均值"補 missing value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')  #或 'median'
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [43]:
from sklearn.metrics import accuracy_score, classification_report

# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9995670058454211
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9236
           1       0.00      0.00      0.00         2

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

precision (精確度): 預測為正例的樣本中，真正為正例的比例。
recall (召回率): 所有真正為正例的樣本中，被正確預測為正例的比例。
f1-score (F1 分數): 精確度和召回率的調和平均值。
support (支持度): 每個類別的樣本數量。
針對每個類別的分析:

類別 0:
precision = 1.00: 所有預測為類別 0 的樣本都是正確的。
recall = 1.00: 所有真正的類別 0 樣本都被正確預測為類別 0。
f1-score = 1.00: 完美！
support = 9236: 測試集中有 9236 個類別 0 的樣本。

類別 1:
precision = 0.00: 所有預測為類別 1 的樣本都不是真正的類別 1。 也就是說，模型根本沒有預測到任何類別 1 的樣本。
recall = 0.00: 模型沒有正確預測任何真正的類別 1 樣本。
f1-score = 0.00: 非常糟糕！
support = 2: 測試集中只有 2 個類別 1 的樣本。

## 2)y = data_ddd['after flag include'] ##

In [51]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['after flag include']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 721) (46854,) 測試集大小: (9238, 721) (9238,)

In [57]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [59]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9981597748430396
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.10      0.11      0.11         9

    accuracy                           1.00      9238
   macro avg       0.55      0.56      0.55      9238
weighted avg       1.00      1.00      1.00      9238

## 3)y = data_ddd['Delist_Flag'] ##

In [61]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['Delist_Flag']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 721) (46854,) 測試集大小: (9238, 721) (9238,)

In [63]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [65]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9984845204589738
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.00      0.00      0.00         9

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

沒有one-hot encoding + 用"中位數"補 missing value

## 1)y = data_ddd['closest flag'] ##

In [87]:
# 按時間分測試集2024和訓練集2019-2023
X = data_ddd.iloc[:, 4:725]  # 特徵欄位
y = data_ddd['closest flag']

# 根據年代分割
X_train = X[data_ddd['fyear'].between(2019, 2023)]
y_train = y[data_ddd['fyear'].between(2019, 2023)]

X_test = X[data_ddd['fyear'] == 2024]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 721) (46854,) 測試集大小: (9238, 721) (9238,)

In [89]:
#用"中位數"補 missing value
imputer = SimpleImputer(strategy='median')  #中位數
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

In [91]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [93]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9991340116908421
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9236
           1       0.00      0.00      0.00         2

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

## 2)y = data_ddd['after flag include'] ##

In [95]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['after flag include']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 721) (46854,) 測試集大小: (9238, 721) (9238,)

In [97]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [99]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9974020350725266
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.00      0.00      0.00         9

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

## 3)y = data_ddd['Delist_Flag'] ##

In [101]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['Delist_Flag']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 721) (46854,) 測試集大小: (9238, 721) (9238,)

In [103]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [105]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9975102836111712
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.00      0.00      0.00         9

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

有one-hot encoding + 用"平均值"補 missing value＋有missing value的dummy

In [132]:
data_x=data_ddd.iloc[:, :725]  # 特徵欄位
data_x

,costat,indfmt,gvkey,exchg,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc
0,A,INDL,1004,11.0,2019,NaN,22.9,92.200,69.300,-44.600,92.200,NaN,1438.700,NaN,0.0,37.200,0.0,0.0,-42.6,0.0,37.200,37.200,191.600,NaN,NaN,NaN,NaN,NaN,NaN,2079.000,25.7173,NaN,478.600,902.600,902.600,776.800,404.700,424.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.700,22.5,0.0,0.0,579.5,NaN,NaN,13.700,672.900,600.000,NaN,670.900,0.000,0.0,NaN,246.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.500,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.500,125.800,10.100,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.800,41.1,NaN,29.9,383.100,NaN,NaN,0.0,NaN,NaN,NaN,122.400,34.400,NaN,NaN,2079.000,1176.400,0.0,16.500,14.500,12.700,10.700,8.300,62.700,36.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.600,NaN,437.100,NaN,683.600,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.400,0.0,-42.6,0.0,22.100,229.100,-2.000,221.200,49.300,NaN,706.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.600,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.700,282.700,0.0,0.000,3.500,0.0,0.0,0.000,3.500,64.900,61.400,0.0,0.000,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.600,136.700,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.400,0.100,0.0,0.0,-3.8,0.0,0.700,NaN,1728.700,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.700,-20.4,NaN,43.700,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.400,150.100,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.800,24.700,NaN,24.800,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.400,4.300,NaN,NaN,NaN,NaN,NaN,NaN,-3.500,-4.000,NaN,NaN,NaN,106.400,150.100,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.400,23.600,6.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.300,NaN,NaN,2089.300,NaN,NaN,NaN,NaN,-63.200,-0.20,-0.20,-6.8,-8.9,NaN,7.300,NaN,NaN,NaN,NaN,NaN,5.100,NaN,NaN,0.500,NaN,NaN,NaN,1.400,2.800,0.0,0.900,5.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.200,NaN,NaN,14.9,NaN,31.100,NaN,210.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.000,NaN,0.000,23.600,23.600,NaN,383.600,NaN,459.5,0.0,0.000,43.700,10.7,1.9,0.000,-1.300,444.500,52.100,52.100,NaN,NaN,NaN,NaN,NaN,24.800,8.600,-98.8,NaN,-1.2,0.0,-24.800,NaN,-36.100,NaN,4.1,NaN,NaN,24.700,NaN,0.0,NaN,0.0,NaN,1.100,NaN,0.0,0.0,0.0,0.500,NaN,NaN,NaN,NaN,-17.0
1,A,INDL,1004,11.0,2020,NaN,19.5,47.200,27.700,-18.300,47.200,NaN,937.000,NaN,0.0,33.900,0.0,0.0,-22.2,0.0,33.900,33.900,127.200,NaN,NaN,NaN,NaN,NaN,NaN,1539.700,27.5449,NaN,479.800,974.400,974.400,825.600,51.800,60.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.500,0.0,0.0,109.5,0.0,NaN,NaN,11.500,195.100,133.700,NaN,193.600,0.000,0.0,NaN,260.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.200,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.000,148.800,29.500,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.400,61.3,NaN,35.4,336.800,NaN,NaN,0.0,NaN,NaN,NaN,25.400,20.000,NaN,NaN,1539.700,565.300,0.0,13.700,11.900,9.900,8.800,7.700,52.000,32.900,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.300,NaN,380.100,NaN,640.300,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.400,0.0,-22.2,0.0,16.400,238.600,3.900,238.600,71.900,NaN,741.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.100,274.100,0.0,9.500,0.000,0.0,0.0,9.500,-9.500,44.500,54.000,0.0,0.700,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.200,136.100,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.800,5.900,0.0,0.0,20.4,0.0,62.100,NaN,1364.600,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.900,-10.5,NaN,36.300,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.500,101.800,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.300,45.900,NaN,46.300,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.800,35.400,NaN,NaN,NaN,NaN,NaN,NaN,-12.100,-12.300,NaN,NaN,NaN,65.500,101.800,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.500,43.700,20.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.400,NaN,NaN,1651.400,3.30,0.09,0.09,4.3,16.100,0.82,0.82,28.6,37.6,NaN,9.200,NaN,NaN,NaN,NaN,NaN,9.800,NaN,NaN,8.400,NaN,NaN,NaN,5.200,3.400,0.0,1.200,18.200,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.600,NaN,NaN,6.2,NaN,21.600,NaN,185.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.500,NaN,0.000,11.300,11.300,NaN,-364.500,NaN,-470.0,0.0,0.000,36.300,0.1,-0.2,0.300,0.000,-469.500,29.000,29.000,NaN,NaN,NaN,NaN,NaN,46.300,4.300,74.9,NaN,10.8,0.0,-0.500,NaN,105.200,NaN,0.0,NaN,NaN,-30.900,NaN,0.0,0.000,20.2,NaN,0.600,NaN,NaN,0.0,0.0,8.400,NaN,NaN,NaN,NaN,-3.3
2,A,INDL,1004,11.0,2021,NaN,16.2,53.900,37.700,-19.600,53.900,NaN,1007.200,NaN,0.0,33.100,0.0,0.0,-16.8,0.0,33.100,33.100,156.400,NaN,NaN,NaN,NaN,NaN,NaN,1573.900,29.2306,NaN,477.500,1034.500,1034.500,892.600,53.500,58.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.100,0.0,100.0,0.0,0.0,NaN,NaN,11.100,157.400,98.900,NaN,156.300,0.000,0.0,NaN,258.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.300,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.800,141.900,25.500,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,37.7,NaN,17.2,348.200,NaN,NaN,0.0,NaN,NaN,NaN,14.900,4.800,NaN,NaN,1573.900,539.400,0.0,13.600,12.400,11.000,9.200,8.500,54.700,25.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.500,NaN,349.200,NaN,607.500,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.800,0.0,-16.8,0.0,17.900,290.300,-2.800,287.600,119.200,NaN,820.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.100,289.100,0.0,20.000,0.000,0.0,0.0,20.000,-20.000,38.500,58.500,0.0,0.000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.000,143.000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.700,-6.700,0.0,0.0,5.4,0.0,77.400,NaN,1470.300,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.900,0.2,NaN,33.100,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.200,149.300,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.500,77.900,NaN,78.500,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.700,78.100,NaN,NaN,NaN,NaN,NaN,NaN,-2.300,-2.400,NaN,NaN,NaN,116.200,149.300,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.100,77.100,28.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.100,NaN,NaN,1817.100,NaN,NaN,NaN,NaN,-6.400,0.01,0.01,0.3,0.2,NaN,8.200,NaN,NaN,NaN,NaN,NaN,17.900,NaN,NaN,8.700,NaN,NaN,NaN,11.000,4.300,0.0,2.600,26.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.800,NaN,NaN,7.3,NaN,32.200,NaN,197.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.500,NaN,0.000,17.300,17.300,NaN,-1.300,NaN,-9.5,0.0,24.700,33.100,0.0,2.9,-0.200,0.000,-59.800,13.700,13.700,NaN,NaN,NaN,NaN,NaN,78.500,2.100,-10.4,NaN,0.8,0.0,-16.500,NaN,75.200,NaN,42.4,NaN,NaN,-50.900,NaN,0.0,NaN,1.7,NaN,16.800,NaN,NaN,0.0,0.0,8.700,NaN,NaN,NaN,NaN,-14.6
3,A,INDL,1004,11.0,2022,NaN,13.5,56.400,42.900,-23.500,56.400,NaN,1097.900,NaN,0.0,32.700,0.0,0.0,-17.8,0.0,32.700,32.700,158.500,NaN,NaN,NaN,NaN,NaN,NaN,1833.100,31.4784,NaN,484.500,1099.100,1099.100,820.000,68.400,81.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.300,0.0,0.0,0.0,272.0,NaN,NaN,12.300,317.900,269.700,NaN,317.900,0.000,0.0,NaN,268.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.800,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.000,279.100,103.300,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,33.1,NaN,13.4,351.500,NaN,NaN,0.0,NaN,NaN,NaN,31.000,18.300,NaN,NaN,1833.100,734.000,0.0,14.500,12.300,9.100,8.400,7.800,52.100,17.600,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.700,NaN,367.900,NaN,636.700,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.100,0.0,-17.8,0.0,13.400,335.000,-5.700,328.200,135.400,NaN,910.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.100,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.800,317.800,0.0,33.600,0.000,0.0,0.0,33.600,-33.600,37.100,70.700,0.0,0.000,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.400,147.600,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.200,-2.900,0.0,0.0,-1.0,0.0,86.300,NaN,1591.300,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.700,0.4,NaN,27.900,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.400,179.300,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.800,88.700,NaN,89.800,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.200,89.100,NaN,NaN,NaN,NaN,NaN,NaN,-3.700,-4.700,NaN,NaN,NaN,151.400,179.300,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.200,87.700,33.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.600,NaN,NaN,1990.600,-1.17,-0.03,-0.03,-1.8,-14.300,-0.07,-0.07,-2.4,-3.1,NaN,13.500,NaN,NaN,NaN,NaN,NaN,33.600,NaN,NaN,-2.200,NaN,NaN,NaN,25.900,4.800,0.0,2.900,31.400,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.300,NaN,NaN,8.0,NaN,29.400,NaN,220.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.300,NaN,103.300,29.500,29.500,NaN,22.900,NaN,172.0,0.0,0.000,27.900,0.0,3.2,-0.100,-1.900,137.700,17.100,17.100,NaN,NaN,NaN,NaN,NaN,89.800,11.100,-20.6,NaN,-5.2,NaN,-138.000,NaN,23.300,NaN,50.1,NaN,NaN,-31.800,NaN,0.0,NaN,0.7,NaN,17.700,NaN,0.0,0.0,0.0,-2.200,34.400,NaN,NaN,NaN,-0.5

In [156]:
data_x.columns

Index(['costat', 'indfmt', 'gvkey', 'exchg', 'fyear', 'acco', 'acdo', 'aco',
       'acodo', 'acominc',
       ...
       'tdc', 'txach', 'txbco', 'txbcof', 'txdc', 'txpd', 'uaoloch', 'udfcc',
       'uois', 'xidoc'],
      dtype='object', length=725)

In [188]:
data_x_d = data_x.drop(['indfmt', 'gvkey', 'exchg'],axis=1) #不轉one hot 因為會太多欄位跑不動
data_x_d

,costat,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc
0,A,2019,NaN,22.9,92.200,69.300,-44.600,92.200,NaN,1438.700,NaN,0.0,37.200,0.0,0.0,-42.6,0.0,37.200,37.200,191.600,NaN,NaN,NaN,NaN,NaN,NaN,2079.000,25.7173,NaN,478.600,902.600,902.600,776.800,404.700,424.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.700,22.5,0.0,0.0,579.5,NaN,NaN,13.700,672.900,600.000,NaN,670.900,0.000,0.0,NaN,246.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.500,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.500,125.800,10.100,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.800,41.1,NaN,29.9,383.100,NaN,NaN,0.0,NaN,NaN,NaN,122.400,34.400,NaN,NaN,2079.000,1176.400,0.0,16.500,14.500,12.700,10.700,8.300,62.700,36.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.600,NaN,437.100,NaN,683.600,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.400,0.0,-42.6,0.0,22.100,229.100,-2.000,221.200,49.300,NaN,706.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.600,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.700,282.700,0.0,0.000,3.500,0.0,0.0,0.000,3.500,64.900,61.400,0.0,0.000,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.600,136.700,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.400,0.100,0.0,0.0,-3.8,0.0,0.700,NaN,1728.700,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.700,-20.4,NaN,43.700,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.400,150.100,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.800,24.700,NaN,24.800,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.400,4.300,NaN,NaN,NaN,NaN,NaN,NaN,-3.500,-4.000,NaN,NaN,NaN,106.400,150.100,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.400,23.600,6.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.300,NaN,NaN,2089.300,NaN,NaN,NaN,NaN,-63.200,-0.20,-0.20,-6.8,-8.9,NaN,7.300,NaN,NaN,NaN,NaN,NaN,5.100,NaN,NaN,0.500,NaN,NaN,NaN,1.400,2.800,0.0,0.900,5.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.200,NaN,NaN,14.9,NaN,31.100,NaN,210.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.000,NaN,0.000,23.600,23.600,NaN,383.600,NaN,459.5,0.0,0.000,43.700,10.7,1.9,0.000,-1.300,444.500,52.100,52.100,NaN,NaN,NaN,NaN,NaN,24.800,8.600,-98.8,NaN,-1.2,0.0,-24.800,NaN,-36.100,NaN,4.1,NaN,NaN,24.700,NaN,0.0,NaN,0.0,NaN,1.100,NaN,0.0,0.0,0.0,0.500,NaN,NaN,NaN,NaN,-17.0
1,A,2020,NaN,19.5,47.200,27.700,-18.300,47.200,NaN,937.000,NaN,0.0,33.900,0.0,0.0,-22.2,0.0,33.900,33.900,127.200,NaN,NaN,NaN,NaN,NaN,NaN,1539.700,27.5449,NaN,479.800,974.400,974.400,825.600,51.800,60.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.500,0.0,0.0,109.5,0.0,NaN,NaN,11.500,195.100,133.700,NaN,193.600,0.000,0.0,NaN,260.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.200,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.000,148.800,29.500,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.400,61.3,NaN,35.4,336.800,NaN,NaN,0.0,NaN,NaN,NaN,25.400,20.000,NaN,NaN,1539.700,565.300,0.0,13.700,11.900,9.900,8.800,7.700,52.000,32.900,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.300,NaN,380.100,NaN,640.300,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.400,0.0,-22.2,0.0,16.400,238.600,3.900,238.600,71.900,NaN,741.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.100,274.100,0.0,9.500,0.000,0.0,0.0,9.500,-9.500,44.500,54.000,0.0,0.700,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.200,136.100,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.800,5.900,0.0,0.0,20.4,0.0,62.100,NaN,1364.600,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.900,-10.5,NaN,36.300,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.500,101.800,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.300,45.900,NaN,46.300,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.800,35.400,NaN,NaN,NaN,NaN,NaN,NaN,-12.100,-12.300,NaN,NaN,NaN,65.500,101.800,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.500,43.700,20.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.400,NaN,NaN,1651.400,3.30,0.09,0.09,4.3,16.100,0.82,0.82,28.6,37.6,NaN,9.200,NaN,NaN,NaN,NaN,NaN,9.800,NaN,NaN,8.400,NaN,NaN,NaN,5.200,3.400,0.0,1.200,18.200,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.600,NaN,NaN,6.2,NaN,21.600,NaN,185.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.500,NaN,0.000,11.300,11.300,NaN,-364.500,NaN,-470.0,0.0,0.000,36.300,0.1,-0.2,0.300,0.000,-469.500,29.000,29.000,NaN,NaN,NaN,NaN,NaN,46.300,4.300,74.9,NaN,10.8,0.0,-0.500,NaN,105.200,NaN,0.0,NaN,NaN,-30.900,NaN,0.0,0.000,20.2,NaN,0.600,NaN,NaN,0.0,0.0,8.400,NaN,NaN,NaN,NaN,-3.3
2,A,2021,NaN,16.2,53.900,37.700,-19.600,53.900,NaN,1007.200,NaN,0.0,33.100,0.0,0.0,-16.8,0.0,33.100,33.100,156.400,NaN,NaN,NaN,NaN,NaN,NaN,1573.900,29.2306,NaN,477.500,1034.500,1034.500,892.600,53.500,58.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.100,0.0,100.0,0.0,0.0,NaN,NaN,11.100,157.400,98.900,NaN,156.300,0.000,0.0,NaN,258.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.300,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.800,141.900,25.500,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,37.7,NaN,17.2,348.200,NaN,NaN,0.0,NaN,NaN,NaN,14.900,4.800,NaN,NaN,1573.900,539.400,0.0,13.600,12.400,11.000,9.200,8.500,54.700,25.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.500,NaN,349.200,NaN,607.500,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.800,0.0,-16.8,0.0,17.900,290.300,-2.800,287.600,119.200,NaN,820.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.100,289.100,0.0,20.000,0.000,0.0,0.0,20.000,-20.000,38.500,58.500,0.0,0.000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.000,143.000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.700,-6.700,0.0,0.0,5.4,0.0,77.400,NaN,1470.300,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.900,0.2,NaN,33.100,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.200,149.300,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.500,77.900,NaN,78.500,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.700,78.100,NaN,NaN,NaN,NaN,NaN,NaN,-2.300,-2.400,NaN,NaN,NaN,116.200,149.300,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.100,77.100,28.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.100,NaN,NaN,1817.100,NaN,NaN,NaN,NaN,-6.400,0.01,0.01,0.3,0.2,NaN,8.200,NaN,NaN,NaN,NaN,NaN,17.900,NaN,NaN,8.700,NaN,NaN,NaN,11.000,4.300,0.0,2.600,26.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.800,NaN,NaN,7.3,NaN,32.200,NaN,197.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.500,NaN,0.000,17.300,17.300,NaN,-1.300,NaN,-9.5,0.0,24.700,33.100,0.0,2.9,-0.200,0.000,-59.800,13.700,13.700,NaN,NaN,NaN,NaN,NaN,78.500,2.100,-10.4,NaN,0.8,0.0,-16.500,NaN,75.200,NaN,42.4,NaN,NaN,-50.900,NaN,0.0,NaN,1.7,NaN,16.800,NaN,NaN,0.0,0.0,8.700,NaN,NaN,NaN,NaN,-14.6
3,A,2022,NaN,13.5,56.400,42.900,-23.500,56.400,NaN,1097.900,NaN,0.0,32.700,0.0,0.0,-17.8,0.0,32.700,32.700,158.500,NaN,NaN,NaN,NaN,NaN,NaN,1833.100,31.4784,NaN,484.500,1099.100,1099.100,820.000,68.400,81.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.300,0.0,0.0,0.0,272.0,NaN,NaN,12.300,317.900,269.700,NaN,317.900,0.000,0.0,NaN,268.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.800,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.000,279.100,103.300,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,33.1,NaN,13.4,351.500,NaN,NaN,0.0,NaN,NaN,NaN,31.000,18.300,NaN,NaN,1833.100,734.000,0.0,14.500,12.300,9.100,8.400,7.800,52.100,17.600,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.700,NaN,367.900,NaN,636.700,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.100,0.0,-17.8,0.0,13.400,335.000,-5.700,328.200,135.400,NaN,910.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.100,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.800,317.800,0.0,33.600,0.000,0.0,0.0,33.600,-33.600,37.100,70.700,0.0,0.000,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.400,147.600,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.200,-2.900,0.0,0.0,-1.0,0.0,86.300,NaN,1591.300,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.700,0.4,NaN,27.900,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.400,179.300,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.800,88.700,NaN,89.800,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.200,89.100,NaN,NaN,NaN,NaN,NaN,NaN,-3.700,-4.700,NaN,NaN,NaN,151.400,179.300,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.200,87.700,33.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.600,NaN,NaN,1990.600,-1.17,-0.03,-0.03,-1.8,-14.300,-0.07,-0.07,-2.4,-3.1,NaN,13.500,NaN,NaN,NaN,NaN,NaN,33.600,NaN,NaN,-2.200,NaN,NaN,NaN,25.900,4.800,0.0,2.900,31.400,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.300,NaN,NaN,8.0,NaN,29.400,NaN,220.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.300,NaN,103.300,29.500,29.500,NaN,22.900,NaN,172.0,0.0,0.000,27.900,0.0,3.2,-0.100,-1.900,137.700,17.100,17.100,NaN,NaN,NaN,NaN,NaN,89.800,11.100,-20.6,NaN,-5.2,NaN,-138.000,NaN,23.300,NaN,50.1,NaN,NaN,-31.800,NaN,0.0,NaN,0.7,NaN,17.700,NaN,0.0,0.0,0.0,-2.200,34.400,NaN,NaN,NaN,-0.5

In [190]:
columns_to_encode = ['costat']  # Replace with your actual column names

# Perform one-hot encoding
data_x_onehot = pd.get_dummies(data_x_d, columns=columns_to_encode, dummy_na=False,dtype=int) 
# Set dummy_na = True if you want NaN to be its own category.

# Print the updated DataFrame info
print(data_x_onehot.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56092 entries, 0 to 56091
Columns: 723 entries, fyear to costat_I
dtypes: float64(720), int64(3)
memory usage: 309.4 MB
None

In [192]:
data_x_onehot

,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc,costat_A,costat_I
0,2019,NaN,22.9,92.200,69.300,-44.600,92.200,NaN,1438.700,NaN,0.0,37.200,0.0,0.0,-42.6,0.0,37.200,37.200,191.600,NaN,NaN,NaN,NaN,NaN,NaN,2079.000,25.7173,NaN,478.600,902.600,902.600,776.800,404.700,424.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.700,22.5,0.0,0.0,579.5,NaN,NaN,13.700,672.900,600.000,NaN,670.900,0.000,0.0,NaN,246.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.500,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.500,125.800,10.100,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.800,41.1,NaN,29.9,383.100,NaN,NaN,0.0,NaN,NaN,NaN,122.400,34.400,NaN,NaN,2079.000,1176.400,0.0,16.500,14.500,12.700,10.700,8.300,62.700,36.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.600,NaN,437.100,NaN,683.600,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.400,0.0,-42.6,0.0,22.100,229.100,-2.000,221.200,49.300,NaN,706.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.600,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.700,282.700,0.0,0.000,3.500,0.0,0.0,0.000,3.500,64.900,61.400,0.0,0.000,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.600,136.700,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.400,0.100,0.0,0.0,-3.8,0.0,0.700,NaN,1728.700,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.700,-20.4,NaN,43.700,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.400,150.100,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.800,24.700,NaN,24.800,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.400,4.300,NaN,NaN,NaN,NaN,NaN,NaN,-3.500,-4.000,NaN,NaN,NaN,106.400,150.100,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.400,23.600,6.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.300,NaN,NaN,2089.300,NaN,NaN,NaN,NaN,-63.200,-0.20,-0.20,-6.8,-8.9,NaN,7.300,NaN,NaN,NaN,NaN,NaN,5.100,NaN,NaN,0.500,NaN,NaN,NaN,1.400,2.800,0.0,0.900,5.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.200,NaN,NaN,14.9,NaN,31.100,NaN,210.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.000,NaN,0.000,23.600,23.600,NaN,383.600,NaN,459.5,0.0,0.000,43.700,10.7,1.9,0.000,-1.300,444.500,52.100,52.100,NaN,NaN,NaN,NaN,NaN,24.800,8.600,-98.8,NaN,-1.2,0.0,-24.800,NaN,-36.100,NaN,4.1,NaN,NaN,24.700,NaN,0.0,NaN,0.0,NaN,1.100,NaN,0.0,0.0,0.0,0.500,NaN,NaN,NaN,NaN,-17.0,1,0
1,2020,NaN,19.5,47.200,27.700,-18.300,47.200,NaN,937.000,NaN,0.0,33.900,0.0,0.0,-22.2,0.0,33.900,33.900,127.200,NaN,NaN,NaN,NaN,NaN,NaN,1539.700,27.5449,NaN,479.800,974.400,974.400,825.600,51.800,60.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.500,0.0,0.0,109.5,0.0,NaN,NaN,11.500,195.100,133.700,NaN,193.600,0.000,0.0,NaN,260.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.200,25.9,NaN,5.4,0.0,-1.5,0.0,0.0,0.0,109.5,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1168.000,148.800,29.500,NaN,NaN,NaN,NaN,NaN,NaN,53.0,591.0,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,29.9,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.400,61.3,NaN,35.4,336.800,NaN,NaN,0.0,NaN,NaN,NaN,25.400,20.000,NaN,NaN,1539.700,565.300,0.0,13.700,11.900,9.900,8.800,7.700,52.000,32.900,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,750.0,25.59,23.93,28.34,18.94,31.56,640.300,NaN,380.100,NaN,640.300,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.400,0.0,-22.2,0.0,16.400,238.600,3.900,238.600,71.900,NaN,741.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,974.400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,274.100,274.100,0.0,9.500,0.000,0.0,0.0,9.500,-9.500,44.500,54.000,0.0,0.700,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.200,136.100,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.800,5.900,0.0,0.0,20.4,0.0,62.100,NaN,1364.600,NaN,NaN,NaN,NaN,NaN,-0.4,NaN,NaN,0.0,45.900,-10.5,NaN,36.300,NaN,NaN,NaN,NaN,NaN,0.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.1,65.500,101.800,NaN,NaN,1.00,1.30,1.01,1.31,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,286.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.300,45.900,NaN,46.300,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,35.800,35.400,NaN,NaN,NaN,NaN,NaN,NaN,-12.100,-12.300,NaN,NaN,NaN,65.500,101.800,0.89,NaN,NaN,NaN,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.500,43.700,20.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.700,-0.33,-0.33,-14.5,0.0,0.0,0.0,0.0,1651.400,NaN,NaN,1651.400,3.30,0.09,0.09,4.3,16.100,0.82,0.82,28.6,37.6,NaN,9.200,NaN,NaN,NaN,NaN,NaN,9.800,NaN,NaN,8.400,NaN,NaN,NaN,5.200,3.400,0.0,1.200,18.200,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.4,-0.15,-0.15,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-10.5,NaN,NaN,NaN,NaN,5.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1549.600,NaN,NaN,6.2,NaN,21.600,NaN,185.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.500,NaN,0.000,11.300,11.300,NaN,-364.500,NaN,-470.0,0.0,0.000,36.300,0.1,-0.2,0.300,0.000,-469.500,29.000,29.000,NaN,NaN,NaN,NaN,NaN,46.300,4.300,74.9,NaN,10.8,0.0,-0.500,NaN,105.200,NaN,0.0,NaN,NaN,-30.900,NaN,0.0,0.000,20.2,NaN,0.600,NaN,NaN,0.0,0.0,8.400,NaN,NaN,NaN,NaN,-3.3,1,0
2,2021,NaN,16.2,53.900,37.700,-19.600,53.900,NaN,1007.200,NaN,0.0,33.100,0.0,0.0,-16.8,0.0,33.100,33.100,156.400,NaN,NaN,NaN,NaN,NaN,NaN,1573.900,29.2306,NaN,477.500,1034.500,1034.500,892.600,53.500,58.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,11.100,0.0,100.0,0.0,0.0,NaN,NaN,11.100,157.400,98.900,NaN,156.300,0.000,0.0,NaN,258.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.300,20.5,NaN,10.1,0.0,-1.1,0.0,0.0,100.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1190.800,141.900,25.500,NaN,NaN,NaN,NaN,NaN,NaN,62.2,604.1,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,33.5,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,37.7,NaN,17.2,348.200,NaN,NaN,0.0,NaN,NaN,NaN,14.900,4.800,NaN,NaN,1573.900,539.400,0.0,13.600,12.400,11.000,9.200,8.500,54.700,25.500,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,850.0,36.17,25.53,29.86,37.84,33.57,607.500,NaN,349.200,NaN,607.500,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800.800,0.0,-16.8,0.0,17.900,290.300,-2.800,287.600,119.200,NaN,820.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1034.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,289.100,289.100,0.0,20.000,0.000,0.0,0.0,20.000,-20.000,38.500,58.500,0.0,0.000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.000,143.000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.700,-6.700,0.0,0.0,5.4,0.0,77.400,NaN,1470.300,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,0.0,77.900,0.2,NaN,33.100,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,116.200,149.300,NaN,NaN,2.17,2.16,2.20,2.19,-2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.500,77.900,NaN,78.500,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,78.700,78.100,NaN,NaN,NaN,NaN,NaN,NaN,-2.300,-2.400,NaN,NaN,NaN,116.200,149.300,2.35,NaN,NaN,NaN,NaN,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.100,77.100,28.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300,-0.10,-0.09,-3.1,0.0,0.0,0.0,0.0,1817.100,NaN,NaN,1817.100,NaN,NaN,NaN,NaN,-6.400,0.01,0.01,0.3,0.2,NaN,8.200,NaN,NaN,NaN,NaN,NaN,17.900,NaN,NaN,8.700,NaN,NaN,NaN,11.000,4.300,0.0,2.600,26.600,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.7,-0.07,-0.08,-3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.2,NaN,NaN,NaN,NaN,2.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1667.800,NaN,NaN,7.3,NaN,32.200,NaN,197.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.500,NaN,0.000,17.300,17.300,NaN,-1.300,NaN,-9.5,0.0,24.700,33.100,0.0,2.9,-0.200,0.000,-59.800,13.700,13.700,NaN,NaN,NaN,NaN,NaN,78.500,2.100,-10.4,NaN,0.8,0.0,-16.500,NaN,75.200,NaN,42.4,NaN,NaN,-50.900,NaN,0.0,NaN,1.7,NaN,16.800,NaN,NaN,0.0,0.0,8.700,NaN,NaN,NaN,NaN,-14.6,1,0
3,2022,NaN,13.5,56.400,42.900,-23.500,56.400,NaN,1097.900,NaN,0.0,32.700,0.0,0.0,-17.8,0.0,32.700,32.700,158.500,NaN,NaN,NaN,NaN,NaN,NaN,1833.100,31.4784,NaN,484.500,1099.100,1099.100,820.000,68.400,81.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.300,1.0000,0.0,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,12.300,0.0,0.0,0.0,272.0,NaN,NaN,12.300,317.900,269.700,NaN,317.900,0.000,0.0,NaN,268.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.800,19.7,NaN,12.7,0.0,0.0,0.0,0.0,0.0,0.0,272.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417.000,279.100,103.300,NaN,NaN,NaN,NaN,NaN,NaN,59.6,624.7,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.8,45.7,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.700,33.1,NaN,13.4,351.500,NaN,NaN,0.0,NaN,NaN,NaN,31.000,18.300,NaN,NaN,1833.100,734.000,0.0,14.500,12.300,9.100,8.400,7.800,52.100,17.600,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,740.0,33.25,25.31,33.24,41.88,35.09,636.700,NaN,367.900,NaN,636.700,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.100,0.0,-17.8,0.0,13.400,335.000,-5.700,328.200,135.400,NaN,910.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.100,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.800,317.800,0.0,33.600,0.000,0.0,0.0,33.600,-33.600,37.100,70.700,0.0,0.000,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.400,147.600,NaN,0.0,NaN,NaN,NaN,NaN,-3.900,-0.11,-0.11,NaN,-6.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.200,-2.900,0.0,0.0,-1.0,0.0,86.300,NaN,1591.300,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,NaN,0.0,88.700,0.4,NaN,27.900,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,151.400,179.300,NaN,NaN,2.53,2.52,2.56,2.55,-3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.800,88.700,NaN,89.800,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,90.200,89.100,NaN,NaN,NaN,NaN,NaN,NaN,-3.700,-4.700,NaN,NaN,NaN,151.400,179.300,2.87,NaN,NaN,NaN,NaN,NaN,NaN,2.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.200,87.700,33.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.400,-0.04,-0.04,-1.9,0.0,0.0,0.0,0.0,1990.600,NaN,NaN,1990.600,-1.17,-0.03,-0.03,-1.8,-14.300,-0.07,-0.07,-2.4,-3.1,NaN,13.500,NaN,NaN,NaN,NaN,NaN,33.600,NaN,NaN,-2.200,NaN,NaN,NaN,25.900,4.800,0.0,2.900,31.400,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.03,-0.03,-1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.4,NaN,NaN,NaN,NaN,12.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811.300,NaN,NaN,8.0,NaN,29.400,NaN,220.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-60.300,NaN,103.300,29.500,29.500,NaN,22.900,NaN,172.0,0.0,0.000,27.900,0.0,3.2,-0.100,-1.900,137.700,17.100,17.100,NaN,NaN,NaN,NaN,NaN,89.800,11.100,-20.6,NaN,-5.2,NaN,-138.000,NaN,23.300,NaN,50.1,NaN,NaN,-31.800,NaN,0.0,NaN,0.7,NaN,17.700,NaN,0.0,0.0,0.0,-2.200,34.400,NaN,NaN,NaN,-0.5,1,0

In [170]:
data_x_onehot.shape

(56092, 723)

In [194]:
data_x_onehot_dummy = data_x_onehot

In [196]:
# 把所有欄位有NaN值的都加一個dummy欄位
for col in data_x_onehot_dummy.columns:
    if data_x_onehot[col].isnull().any():  # 檢查欄位是否包含 NaN 值
        new_col_name = col + '_missing'  # 建立新的 dummy 欄位名稱
        data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
data_x_onehot_dummy.head()

/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位
/var/folders/36/hd8g5yqj6dnflvczdcddf9900000gn/T/ipykernel_2135/588847031.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_x_onehot[new_col_name] = data_x_onehot[col].isnull().astype(int)  # 建立 dummy 欄位

,fyear,acco,acdo,aco,acodo,acominc,acox,acoxar,act,aedi,aldo,ao,aocidergl,aociother,aocipen,aocisecgl,aodo,aox,ap,apb,apc,apofs,arb,arc,artfs,at,bkvlps,ca,caps,ceq,ceql,ceqt,ch,che,chs,cld2,cld3,cld4,cld5,clfc,clfx,clg,clis,cll,cllc,clo,clrll,clt,cmp,crv,crvnli,cstk,cstkcv,dc,dclo,dcom,dcpstk,dcs,dcvsr,dcvsub,dcvt,dd,dd1,dd2,dd3,dd4,dd5,dfpac,dfs,dlc,dlto,dltp,dltsub,dltt,dm,dn,dpacre,dpact,dpdc,dpltb,dpsc,dpstb,dptb,dptc,dptic,dpvieb,drc,drci,drlt,ds,dudd,dvpa,dxd2,dxd3,dxd4,dxd5,ea,esopct,esopdlt,esopnr,esopr,esopt,excadj,fatb,fatc,fate,fatl,fatn,fato,fatp,fdfr,fea,fel,ffs,gdwl,geqrv,govgr,iaeq,iaeqci,iaeqmi,iafici,iafxi,iafxmi,iali,ialoi,ialti,iamli,iaoi,iapli,iarei,iasci,iasmi,iassi,iasti,iatci,iati,iatmi,iaui,icapt,intan,intano,invfg,invo,invofs,invreh,invrei,invres,invrm,invt,invwip,ip,ipc,ipv,iseq,iseqc,iseqm,isfi,isfxc,isfxm,islg,islgc,islgm,islt,isng,isngc,isngm,isotc,isoth,isotm,issc,issm,issu,ist,istc,istm,isut,itcb,ivaeq,ivao,ivgod,ivpt,ivst,lcabg,lcacl,lcacr,lcag,lcal,lcalt,lcam,lcao,lcast,lcat,lco,lcox,lcoxar,lcoxdr,lct,lcuacu,lif,lifr,lloml,lloo,llot,lo,loxdr,lrv,ls,lse,lt,mib,mrc1,mrc2,mrc3,mrc4,mrc5,mrct,mrcta,msa,msvrv,mtl,np,npanl,npaore,nparl,npat,ob,optprcca,optprcex,optprcey,optprcgr,optprcwa,ppegt,ppenc,ppent,ppevbb,ppeveb,prc,prodv,prvt,pstk,pstkc,pstkl,pstkn,pstkr,pstkrv,pvcl,pvpl,pvt,radp,ragr,rari,rati,rcl,rdp,re,rea,reajo,recco,recd,rect,recta,rectr,recub,ret,reuna,reunr,rll,rlo,rlp,rlri,rlt,rpag,rvbci,rvbpi,rvbti,rvdo,rvdt,rveqt,rvlrv,rvno,rvnt,rvri,rvsi,rvti,rvtxr,rvupi,rvutx,saa,sal,sbdc,sc,sco,secu,seq,seqo,srt,ssnp,stbo,stio,tdscd,tdsce,tdslg,tdsmm,tdsng,tdso,tdss,tdst,tlcf,transa,tsa,tso,tstk,tstkc,tstkp,txdb,txdba,txdbca,txdbcl,txditc,txndb,txndba,txndbl,txndbr,txp,txr,uaox,uapt,ucaps,uccons,uceq,ucustad,udcopres,udd,udmb,udolt,udpco,ui,uinvt,ulcm,ulco,unl,unnp,unnpl,uopres,upmcstk,upmpf,upmpfs,upmsubp,upstk,upstkc,upstksf,urect,urectr,urevub,usubpstk,vpac,vpo,wcap,xacc,xpp,acchg,adpac,am,amdc,amgw,aqa,aqd,aqeps,aqi,aqp,aqs,autxr,balr,banlr,batr,bcef,bclr,bcltbl,bcnlr,bcrbl,bct,bctbl,bctr,bltbl,cbi,cdpac,cfbd,cfere,cfo,cfpdo,cga,cgri,cgti,cgui,cibegni,cicurr,cidergl,ciother,cipen,cisecgl,citotal,cnltbl,cogs,cpcbl,cpdoi,cpnli,cppbl,cprei,cstke,dbi,dfxa,diladj,dilavx,do,donr,dp,dpret,dtea,dted,dteeps,dtep,dvc,dvdnp,dvp,dvpd,dvpdp,dvrpiv,dvrre,dvsco,dvt,ebit,ebitda,eiea,emol,epsfi,epsfx,epspi,epspx,esub,fatd,fca,ffo,gbbl,gdwlia,gdwlid,gdwlieps,gdwlip,gla,glcea,glced,glceeps,glcep,gld,gleps,glp,gp,gphbl,gplbl,gpobl,gprbl,gptbl,gwo,hedgegl,ib,ibadj,ibbl,ibcom,ibki,idiis,idilb,idilc,idis,idist,idit,idits,iire,initb,intc,iobd,ioi,iore,ipabl,iphbl,iplbl,ipobl,iptbl,ipti,irei,irent,irii,irli,irnli,irsi,isgr,isgt,isgu,itci,ivi,li,llrci,llrcr,llwoci,llwocr,lst,mii,nco,nfsr,ni,niadj,niint,niit,nim,nio,nit,nits,nopi,nopio,nrtxt,nrtxtd,nrtxteps,oiadp,oibdp,opeps,opili,opincar,opini,opioi,opiri,opiti,oprepsx,palr,panlr,patr,pcl,pclr,pcnlr,pctr,pi,pidom,pifo,pll,pltbl,pnca,pncad,pncaeps,pnlbl,pnli,pobl,ppcbl,pppabl,ppphbl,pppobl,ppptbl,prca,prcad,prcaeps,prebl,pri,ptbl,ptran,pvo,pvon,pwoi,rca,rcd,rceps,rcp,rdip,rdipa,rdipd,rdipeps,revt,ris,rmum,sale,seta,setd,seteps,setp,spi,spid,spieps,spioa,spiop,sret,stkco,stkcpa,tdsg,tf,tie,tii,txc,txdfed,txdfo,txdi,txds,txeqa,txeqii,txfed,txfo,txo,txs,txt,txva,txw,udpfa,udvp,ugi,uniami,unopinc,uopi,updvp,uspi,usubdvp,utme,utxfed,uxinst,uxintd,wda,wdd,wdeps,wdp,xad,xago,xagt,xcom,xcomi,xdvre,xeqo,xi,xido,xindb,xindc,xins,xinst,xint,xintd,xivi,xivre,xlr,xnbi,xnf,xnins,xnitb,xobd,xoi,xopr,xoprar,xore,xpr,xrd,xrent,xs,xsga,xstf,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,afudcc,afudci,amc,aoloch,apalch,aqc,capx,capxv,cdvc,chech,depc,dlcch,dltis,dltr,dpc,dv,esubc,exre,fiao,fincf,fopo,fopox,fopt,fsrco,fsrct,fuseo,fuset,ibc,intpn,invch,itcc,ivaco,ivch,ivncf,ivstch,oancf,pdvc,prstkc,prstkcc,prstkpc,recch,scstkc,siv,sppe,sppiv,spstkc,sstk,tdc,txach,txbco,txbcof,txdc,txpd,uaoloch,udfcc,uois,xidoc,costat_A,costat_I,acco_missing,acdo_missing,aco_missing,acodo_missing,acominc_missing,acox_missing,acoxar_missing,act_missing,aedi_missing,aldo_missing,ao_missing,aocidergl_missing,aociother_missing,aocipen_missing,aocisecgl_missing,aodo_missing,aox_missing,ap_missing,apb_missing,apc_missing,apofs_missing,arb_missing,arc_missing,artfs_missing,at_missing,bkvlps_missing,ca_missing,caps_missing,ceq_missing,ceql_missing,ceqt_missing,ch_missing,che_missing,chs_missing,cld2_missing,cld3_missing,cld4_missing,cld5_missing,clfc_missing,clfx_missing,clg_missing,clis_missing,cll_missing,cllc_missing,clo_missing,clrll_missing,clt_missing,cmp_missing,crv_missing,crvnli_missing,cstk_missing,cstkcv_missing,dc_missing,dclo_missing,dcom_missing,dcpstk_missing,dcs_missing,dcvsr_missing,dcvsub_missing,dcvt_missing,dd_missing,dd1_missing,dd2_missing,dd3_missing,dd4_missing,dd5_missing,dfpac_missing,dfs_missing,dlc_missing,dlto_missing,dltp_missing,dltsub_missing,dltt_missing,dm_missing,dn_missing,dpacre_missing,dpact_missing,dpdc_missing,dpltb_missing,dpsc_missing,dpstb_missing,dptb_missing,dptc_missing,dptic_missing,dpvieb_missing,drc_missing,drci_missing,drlt_missing,ds_missing,dudd_missing,dvpa_missing,dxd2_missing,dxd3_missing,dxd4_missing,dxd5_missing,ea_missing,esopct_missing,esopdlt_missing,esopnr_missing,esopr_missing,esopt_missing,excadj_missing,fatb_missing,fatc_missing,fate_missing,fatl_missing,fatn_missing,fato_missing,fatp_missing,fdfr_missing,fea_missing,fel_missing,ffs_missing,gdwl_missing,geqrv_missing,govgr_missing,iaeq_missing,iaeqci_missing,iaeqmi_missing,iafici_missing,iafxi_missing,iafxmi_missing,iali_missing,ialoi_missing,ialti_missing,iamli_missing,iaoi_missing,iapli_missing,iarei_missing,iasci_missing,iasmi_missing,iassi_missing,iasti_missing,iatci_missing,iati_missing,iatmi_missing,iaui_missing,icapt_missing,intan_missing,intano_missing,invfg_missing,invo_missing,invofs_missing,invreh_missing,invrei_missing,invres_missing,invrm_missing,invt_missing,invwip_missing,ip_missing,ipc_missing,ipv_missing,iseq_missing,iseqc_missing,iseqm_missing,isfi_missing,isfxc_missing,isfxm_missing,islg_missing,islgc_missing,islgm_missing,islt_missing,isng_missing,isngc_missing,isngm_missing,isotc_missing,isoth_missing,isotm_missing,issc_missing,issm_missing,issu_missing,ist_missing,istc_missing,istm_missing,isut_missing,itcb_missing,ivaeq_missing,ivao_missing,ivgod_missing,ivpt_missing,ivst_missing,lcabg_missing,lcacl_missing,lcacr_missing,lcag_missing,lcal_missing,lcalt_missing,lcam_missing,lcao_missing,lcast_missing,lcat_missing,lco_missing,lcox_missing,lcoxar_missing,lcoxdr_missing,lct_missing,lcuacu_missing,lif_missing,lifr_missing,lloml_missing,lloo_missing,llot_missing,lo_missing,loxdr_missing,lrv_missing,ls_missing,lse_missing,lt_missing,mib_missing,mrc1_missing,mrc2_missing,mrc3_missing,mrc4_missing,mrc5_missing,mrct_missing,mrcta_missing,msa_missing,msvrv_missing,mtl_missing,np_missing,npanl_missing,npaore_missing,nparl_missing,npat_missing,ob_missing,optprcca_missing,optprcex_missing,optprcey_missing,optprcgr_missing,optprcwa_missing,ppegt_missing,ppenc_missing,ppent_missing,ppevbb_missing,ppeveb_missing,prc_missing,prodv_missing,prvt_missing,pstk_missing,pstkc_missing,pstkl_missing,pstkn_missing,pstkr_missing,pstkrv_missing,pvcl_missing,pvpl_missing,pvt_missing,radp_missing,ragr_missing,rari_missing,rati_missing,rcl_missing,rdp_missing,re_missing,rea_missing,reajo_missing,recco_missing,recd_missing,rect_missing,recta_missing,rectr_missing,recub_missing,ret_missing,reuna_missing,reunr_missing,rll_missing,rlo_missing,rlp_missing,rlri_missing,rlt_missing,rpag_missing,rvbci_missing,rvbpi_missing,rvbti_missing,rvdo_missing,rvdt_missing,rveqt_missing,rvlrv_missing,rvno_missing,rvnt_missing,rvri_missing,rvsi_missing,rvti_missing,rvtxr_missing,rvupi_missing,rvutx_missing,saa_missing,sal_missing,sbdc_missing,sc_missing,sco_missing,secu_missing,seq_missing,seqo_missing,srt_missing,ssnp_missing,stbo_missing,stio_missing,tdscd_missing,tdsce_missing,tdslg_missing,tdsmm_missing,tdsng_missing,tdso_missing,tdss_missing,tdst_missing,tlcf_missing,transa_missing,tsa_missing,tso_missing,tstk_missing,tstkc_missing,tstkp_missing,txdb_missing,txdba_missing,txdbca_missing,txdbcl_missing,txditc_missing,txndb_missing,txndba_missing,txndbl_missing,txndbr_missing,txp_missing,txr_missing,uaox_missing,uapt_missing,ucaps_missing,uccons_missing,uceq_missing,ucustad_missing,udcopres_missing,udd_missing,udmb_missing,udolt_missing,udpco_missing,ui_missing,uinvt_missing,ulcm_missing,ulco_missing,unl_missing,unnp_missing,unnpl_missing,uopres_missing,upmcstk_missing,upmpf_missing,upmpfs_missing,upmsubp_missing,upstk_missing,upstkc_missing,upstksf_missing,urect_missing,urectr_missing,urevub_missing,usubpstk_missing,vpac_missing,vpo_missing,wcap_missing,xacc_missing,xpp_missing,acchg_missing,adpac_missing,am_missing,amdc_missing,amgw_missing,aqa_missing,aqd_missing,aqeps_missing,aqi_missing,aqp_missing,aqs_missing,autxr_missing,balr_missing,banlr_missing,batr_missing,bcef_missing,bclr_missing,bcltbl_missing,bcnlr_missing,bcrbl_missing,bct_missing,bctbl_missing,bctr_missing,bltbl_missing,cbi_missing,cdpac_missing,cfbd_missing,cfere_missing,cfo_missing,cfpdo_missing,cga_missing,cgri_missing,cgti_missing,cgui_missing,cibegni_missing,cicurr_missing,cidergl_missing,ciother_missing,cipen_missing,cisecgl_missing,citotal_missing,cnltbl_missing,cogs_missing,cpcbl_missing,cpdoi_missing,cpnli_missing,cppbl_missing,cprei_missing,cstke_missing,dbi_missing,dfxa_missing,diladj_missing,dilavx_missing,do_missing,donr_missing,dp_missing,dpret_missing,dtea_missing,dted_missing,dteeps_missing,dtep_missing,dvc_missing,dvdnp_missing,dvp_missing,dvpd_missing,dvpdp_missing,dvrpiv_missing,dvrre_missing,dvsco_missing,dvt_missing,ebit_missing,ebitda_missing,eiea_missing,emol_missing,epsfi_missing,epsfx_missing,epspi_missing,epspx_missing,esub_missing,fatd_missing,fca_missing,ffo_missing,gbbl_missing,gdwlia_missing,gdwlid_missing,gdwlieps_missing,gdwlip_missing,gla_missing,glcea_missing,glced_missing,glceeps_missing,glcep_missing,gld_missing,gleps_missing,glp_missing,gp_missing,gphbl_missing,gplbl_missing,gpobl_missing,gprbl_missing,gptbl_missing,gwo_missing,hedgegl_missing,ib_missing,ibadj_missing,ibbl_missing,ibcom_missing,ibki_missing,idiis_missing,idilb_missing,idilc_missing,idis_missing,idist_missing,idit_missing,idits_missing,iire_missing,initb_missing,intc_missing,iobd_missing,ioi_missing,iore_missing,ipabl_missing,iphbl_missing,iplbl_missing,ipobl_missing,iptbl_missing,ipti_missing,irei_missing,irent_missing,irii_missing,irli_missing,irnli_missing,irsi_missing,isgr_missing,isgt_missing,isgu_missing,itci_missing,ivi_missing,li_missing,llrci_missing,llrcr_missing,llwoci_missing,llwocr_missing,lst_missing,mii_missing,nco_missing,nfsr_missing,ni_missing,niadj_missing,niint_missing,niit_missing,nim_missing,nio_missing,nit_missing,nits_missing,nopi_missing,nopio_missing,nrtxt_missing,nrtxtd_missing,nrtxteps_missing,oiadp_missing,oibdp_missing,opeps_missing,opili_missing,opincar_missing,opini_missing,opioi_missing,opiri_missing,opiti_missing,oprepsx_missing,palr_missing,panlr_missing,patr_missing,pcl_missing,pclr_missing,pcnlr_missing,pctr_missing,pi_missing,pidom_missing,pifo_missing,pll_missing,pltbl_missing,pnca_missing,pncad_missing,pncaeps_missing,pnlbl_missing,pnli_missing,pobl_missing,ppcbl_missing,pppabl_missing,ppphbl_missing,pppobl_missing,ppptbl_missing,prca_missing,prcad_missing,prcaeps_missing,prebl_missing,pri_missing,ptbl_missing,ptran_missing,pvo_missing,pvon_missing,pwoi_missing,rca_missing,rcd_missing,rceps_missing,rcp_missing,rdip_missing,rdipa_missing,rdipd_missing,rdipeps_missing,revt_missing,ris_missing,rmum_missing,sale_missing,seta_missing,setd_missing,seteps_missing,setp_missing,spi_missing,spid_missing,spieps_missing,spioa_missing,spiop_missing,sret_missing,stkco_missing,stkcpa_missing,tdsg_missing,tf_missing,tie_missing,tii_missing,txc_missing,txdfed_missing,txdfo_missing,txdi_missing,txds_missing,txeqa_missing,txeqii_missing,txfed_missing,txfo_missing,txo_missing,txs_missing,txt_missing,txva_missing,txw_missing,udpfa_missing,udvp_missing,ugi_missing,uniami_missing,unopinc_missing,uopi_missing,updvp_missing,uspi_missing,usubdvp_missing,utme_missing,utxfed_missing,uxinst_missing,uxintd_missing,wda_missing,wdd_missing,wdeps_missing,wdp_missing,xad_missing,xago_missing,xagt_missing,xcom_missing,xcomi_missing,xdvre_missing,xeqo_missing,xi_missing,xido_missing,xindb_missing,xindc_missing,xins_missing,xinst_missing,xint_missing,xintd_missing,xivi_missing,xivre_missing,xlr_missing,xnbi_missing,xnf_missing,xnins_missing,xnitb_missing,xobd_missing,xoi_missing,xopr_missing,xoprar_missing,xore_missing,xpr_missing,xrd_missing,xrent_missing,xs_missing,xsga_missing,xstf_missing,xstfo_missing,xstfws_missing,xt_missing,xuw_missing,xuwli_missing,xuwnli_missing,xuwoi_missing,xuwrei_missing,xuwti_missing,afudcc_missing,afudci_missing,amc_missing,aoloch_missing,apalch_missing,aqc_missing,capx_missing,capxv_missing,cdvc_missing,chech_missing,depc_missing,dlcch_missing,dltis_missing,dltr_missing,dpc_missing,dv_missing,esubc_missing,exre_missing,fiao_missing,fincf_missing,fopo_missing,fopox_missing,fopt_missing,fsrco_missing,fsrct_missing,fuseo_missing,fuset_missing,ibc_missing,intpn_missing,invch_missing,itcc_missing,ivaco_missing,ivch_missing,ivncf_missing,ivstch_missing,oancf_missing,pdvc_missing,prstkc_missing,prstkcc_missing,prstkpc_missing,recch_missing,scstkc_missing,siv_missing,sppe_missing,sppiv_missing,spstkc_missing,sstk_missing,tdc_missing,txach_missing,txbco_missing,txbcof_missing,txdc_missing,txpd_missing,uaoloch_missing,udfcc_missing,uois_missing,xidoc_missing
0,2019,NaN,22.9,92.2,69.3,-44.6,92.2,NaN,1438.7,NaN,0.0,37.2,0.0,0.0,-42.6,0.0,37.2,37.2,191.6,NaN,NaN,NaN,NaN,NaN,NaN,2079.0,25.7173,NaN,478.6,902.6,902.6,776.8,404.7,424.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.3,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,13.7,22.5,0.0,0.0,579.5,NaN,NaN,13.7,672.9,600.0,NaN,670.9,0.0,0.0,NaN,246.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.5,11.2,NaN,88.0,0.0,-2.0,0.0,22.5,0.0,0.0,579.5,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.5,125.8,10.1,NaN,NaN,NaN,NaN,NaN,NaN,45.9,692.7,20.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.6,27.6,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.8,41.1,NaN,29.9,383.1,NaN,NaN,0.0,NaN,NaN,NaN,122.4,34.4,NaN,NaN,2079.0,1176.4,0.0,16.5,14.5,12.7,10.7,8.3,62.7,36.5,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1000.0,36.72,24.99,32.74,37.66,28.32,683.6,NaN,437.1,NaN,683.6,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,661.4,0.0,-42.6,0.0,22.1,229.1,-2.0,221.2,49.3,NaN,706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,282.7,282.7,0.0,0.0,3.5,0.0,0.0,0.0,3.5,64.9,61.4,0.0,0.0,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.6,136.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.4,0.1,0.0,0.0,-3.8,0.0,0.7,NaN,1728.7,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,0.0,24.7,-20.4,NaN,43.7,NaN,NaN,NaN,NaN,NaN,10.7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.7,106.4,150.1,NaN,NaN,0.13,0.71,0.12,0.71,-1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.8,24.7,NaN,24.8,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.4,4.3,NaN,NaN,NaN,NaN,NaN,NaN,-3.5,-4.0,NaN,NaN,NaN,106.4,150.1,2.16,NaN,NaN,NaN,NaN,NaN,NaN,2.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.4,23.6,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.900,-0.99,-1.00,-43.7,0.0,0.0,0.0,0.0,2089.3,NaN,NaN,2089.3,NaN,NaN,NaN,NaN,-63.2,-0.20,-0.20,-6.8,-8.9,NaN,7.3,NaN,NaN,NaN,NaN,NaN,5.1,NaN,NaN,0.5,NaN,NaN,NaN,1.4,2.8,0.0,0.9,5.6,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.7,-0.25,-0.25,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.4,NaN,NaN,NaN,NaN,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.2,NaN,NaN,14.9,NaN,31.1,NaN,210.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.0,NaN,0.0,23.6,23.6,NaN,383.6,NaN,459.5,0.0,0.0,43.7,10.7,1.9,0.0,-1.3,444.5,52.1,52.1,NaN,NaN,NaN,NaN,NaN,24.8,8.6,-98.8,NaN,-1.2,0.0,-24.8,NaN,-36.1,NaN,4.1,NaN,NaN,24.7,NaN,0.0,NaN,0.0,NaN,1.1,NaN,0.0,0.0,0.0,0.5,NaN,NaN,NaN,NaN,-17.0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,1,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,1,1,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,1,1,0,0,0,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,1,0,1,1,1,1,1,0,1,1,0,1,1,1,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,1,0,0,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,0,0,0,1,1,1,1,0

In [198]:
data_x_onehot_dummy.shape

(56092, 1443)

In [146]:
data_x_onehot.shape #原本indfmt', 'gvkey', 'exchg'也轉 one hot

(56092, 12166)

## 1)y = data_ddd['closest flag'] ##

In [224]:
# 按時間分測試集2024和訓練集2019-2023
X = data_x_onehot_dummy  # 特徵欄位
y = data_ddd['closest flag']

# 根據年代分割
X_train = X[data_x_onehot_dummy['fyear'].between(2019, 2023)]
y_train = y[data_ddd['fyear'].between(2019, 2023)]

X_test = X[data_x_onehot_dummy['fyear'] == 2024]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 1443) (46854,) 測試集大小: (9238, 1443) (9238,)

In [206]:
#用"平均值"補 missing value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')  #或 'median'
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/impute/_base.py:653: UserWarning: Skipping features without any observed values: ['uxinst']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

In [208]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [210]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9994587573067764
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9236
           1       0.00      0.00      0.00         2

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

## 2)y = data_ddd['after flag include'] ##

In [212]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['after flag include']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 1443) (46854,) 測試集大小: (9238, 1443) (9238,)

In [214]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [216]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9988092660749079
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.25      0.11      0.15         9

    accuracy                           1.00      9238
   macro avg       0.62      0.56      0.58      9238
weighted avg       1.00      1.00      1.00      9238

## 3)y = data_ddd['Delist_Flag'] ##

In [218]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['Delist_Flag']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 1443) (46854,) 測試集大小: (9238, 1443) (9238,)

In [220]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1000)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [222]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9985927689976185
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.00      0.00      0.00         9

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

有one-hot encoding + 用"平均值"補 missing value＋有missing value的dummy 且max_iter=1500 （但以下結果沒有更好）

## 1)y = data_ddd['closest flag'] ##

In [ ]:
# 按時間分測試集2024和訓練集2019-2023
X = data_x_onehot_dummy  # 特徵欄位
y = data_ddd['closest flag']

# 根據年代分割
X_train = X[data_x_onehot_dummy['fyear'].between(2019, 2023)]
y_train = y[data_ddd['fyear'].between(2019, 2023)]

X_test = X[data_x_onehot_dummy['fyear'] == 2024]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

In [226]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1500)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1500 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1500).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1500)

In [228]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9992422602294869
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9236
           1       0.00      0.00      0.00         2

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238

## 2)y = data_ddd['after flag include'] ##

In [230]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['after flag include']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 1443) (46854,) 測試集大小: (9238, 1443) (9238,)

In [232]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1500)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1500 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1500).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1500)

In [234]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9982680233816843
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.11      0.11      0.11         9

    accuracy                           1.00      9238
   macro avg       0.56      0.56      0.56      9238
weighted avg       1.00      1.00      1.00      9238

## 3)y = data_ddd['Delist_Flag'] ##

In [236]:
# 按時間分測試集2024和訓練集2019-2023
y = data_ddd['Delist_Flag']

# 根據年代分割
y_train = y[data_ddd['fyear'].between(2019, 2023)]
y_test = y[data_ddd['fyear'] == 2024]

# 確認分割結果
print("訓練集大小:", X_train.shape,y_train.shape, "測試集大小:", X_test.shape,y_test.shape)

訓練集大小: (46854, 1443) (46854,) 測試集大小: (9238, 1443) (9238,)

In [238]:
# 模型如前相同定義
model = LogisticRegression(max_iter=1500)
model.fit(X_train_imputed, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1500 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1500).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1500)

In [240]:
# 預測
y_pred = model.predict(X_test_imputed)

# 評估
accuracy = accuracy_score(y_test, y_pred)
print("準確度:", accuracy)
print("分類報告:\n", classification_report(y_test, y_pred))

準確度: 0.9980515263043949
分類報告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.00      0.00      0.00         9

    accuracy                           1.00      9238
   macro avg       0.50      0.50      0.50      9238
weighted avg       1.00      1.00      1.00      9238