In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
tej = pd.read_csv('tej.csv', skipinitialspace=True)
tcri = pd.read_csv('tcri.csv')
tej.columns = tej.columns.str.strip()

In [2]:
tej.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21767 entries, 0 to 21766
Data columns (total 54 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   公司                 21767 non-null  object
 1   年/月                21767 non-null  object
 2   季別                 21767 non-null  int64
 3   合併(Y/N)            21767 non-null  object
 4   月份                 21767 non-null  int64
 5   幣別                 21767 non-null  object
 6   現金及約當現金            21767 non-null  object
 7   流動資產               21767 non-null  object
 8   資產總額               21767 non-null  object
 9   流動負債               21767 non-null  object
 10  負債總額               21767 non-null  object
 11  普通股股本              21767 non-null  object
 12  股本                 21767 non-null  object
 13  資本公積合計             21767 non-null  object
 14  保留盈餘               21767 non-null  object
 15  股東權益總額             21767 non-null  object
 16  營業收入淨額             21767 non-null  object
 17  營業成本               21767 non-null  object
 18  營業毛利               21767 non-null  object
 19  營業費用               21767 non-null  object
 20  營運資金               21767 non-null  object
 21  研究發展費              21767 non-null  object
 22  預期信用減損（損失）利益－營業費用  21767 non-null  object
 23  營業利益               21767 non-null  object
 24  財務成本               21767 non-null  object
 25  稅前淨利               21767 non-null  object
 26  稅前息前淨利             21767 non-null  object
 27  來自營運之現金流量          21767 non-null  object
 28  投資活動之現金流量          21767 non-null  object
 29  籌資活動之現金流量          21767 non-null  object
 30  Tobins Q           21767 non-null  object
 31  財務槓桿度              21767 non-null  object
 32  營運槓桿度              21767 non-null  object
 33  利息保障倍數             21767 non-null  object
 34  ROA－綜合損益           21767 non-null  object
 35  ROE－綜合損益           21767 non-null  object
 36  現金流量允當比            21767 non-null  object
 37  現金再投資比             21767 non-null  object
 38  流動比率               21767 non-null  object
 39  速動比率               21767 non-null  object
 40  利息支出率              21767 non-null  object
 41  利息支出率(B)           21767 non-null  object
 42  總負債/總淨值            21767 non-null  object
 43  負債比率               21767 non-null  float64
 44  淨值/資產              21767 non-null  float64
 45  長期資金適合率(A)         21767 non-null  object
 46  長短期借款              21767 non-null  object
 47  淨負債                21767 non-null  object
 48  借款依存度              21767 non-null  object
 49  或有負債/淨值            21767 non-null  object
 50  營業利益 /實收資本比        21767 non-null  object
 51  稅前純益 /實收資本         21767 non-null  object
 52  內部保留比率             21767 non-null  object
 53  股利支付率              21767 non-null  object
dtypes: float64(2), int64(2), object(50)
memory usage: 9.0+ MB

In [3]:
tcri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14142 entries, 0 to 14141
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   coid    14142 non-null  int64
 1   mdate   14142 non-null  object
 2   tcri    14142 non-null  object
 3   scr     14126 non-null  float64
 4   xcdt    226 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 552.6+ KB

In [4]:
tcri['mdate'] = pd.to_datetime(tcri['mdate']).dt.year
tcri

       coid  mdate tcri    scr xcdt
0      1103   2014    6  400.0  NaN
1      1103   2015    6  432.0  NaN
2      1103   2016    6  371.0  NaN
3      1103   2017    6  330.0  NaN
4      1103   2018    6  331.0  NaN
...     ...    ...  ...    ...  ...
14137  9962   2020    6  376.0  NaN
14138  9962   2021    6  418.0  NaN
14139  9962   2022    6  599.0  NaN
14140  9962   2023    6  494.0  NaN
14141  9962   2024    6  293.0  NaN

[14142 rows x 5 columns]

### 合併

In [5]:
tej['公司編號'] = tej['公司'].str.extract('(\d+)').astype(int)
tej['年份'] = tej['年/月'].str.split('/').str[0].astype(int)
tej['月份'] = tej['年/月'].str.split('/').str[1].astype(int)
tej_december = tej[tej['月份'] == 12].copy()

tcri['coid'] = tcri['coid'].astype(int)
tcri['mdate'] = tcri['mdate'].astype(int)

# 合併
merged_data = tej_december.merge(
    tcri[['coid', 'mdate', 'tcri']], 
    left_on=['公司編號', '年份'], 
    right_on=['coid', 'mdate'], 
    how='left'
)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\jack9\AppData\Local\Temp\ipykernel_9776\4288742798.py:1: SyntaxWarning: invalid escape sequence '\d'
  tej['公司編號'] = tej['公司'].str.extract('(\d+)').astype(int)

In [6]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11014 entries, 0 to 11013
Data columns (total 59 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   公司                 11014 non-null  object
 1   年/月                11014 non-null  object
 2   季別                 11014 non-null  int64
 3   合併(Y/N)            11014 non-null  object
 4   月份                 11014 non-null  int32
 5   幣別                 11014 non-null  object
 6   現金及約當現金            11014 non-null  object
 7   流動資產               11014 non-null  object
 8   資產總額               11014 non-null  object
 9   流動負債               11014 non-null  object
 10  負債總額               11014 non-null  object
 11  普通股股本              11014 non-null  object
 12  股本                 11014 non-null  object
 13  資本公積合計             11014 non-null  object
 14  保留盈餘               11014 non-null  object
 15  股東權益總額             11014 non-null  object
 16  營業收入淨額             11014 non-null  object
 17  營業成本               11014 non-null  object
 18  營業毛利               11014 non-null  object
 19  營業費用               11014 non-null  object
 20  營運資金               11014 non-null  object
 21  研究發展費              11014 non-null  object
 22  預期信用減損（損失）利益－營業費用  11014 non-null  object
 23  營業利益               11014 non-null  object
 24  財務成本               11014 non-null  object
 25  稅前淨利               11014 non-null  object
 26  稅前息前淨利             11014 non-null  object
 27  來自營運之現金流量          11014 non-null  object
 28  投資活動之現金流量          11014 non-null  object
 29  籌資活動之現金流量          11014 non-null  object
 30  Tobins Q           11014 non-null  object
 31  財務槓桿度              11014 non-null  object
 32  營運槓桿度              11014 non-null  object
 33  利息保障倍數             11014 non-null  object
 34  ROA－綜合損益           11014 non-null  object
 35  ROE－綜合損益           11014 non-null  object
 36  現金流量允當比            11014 non-null  object
 37  現金再投資比             11014 non-null  object
 38  流動比率               11014 non-null  object
 39  速動比率               11014 non-null  object
 40  利息支出率              11014 non-null  object
 41  利息支出率(B)           11014 non-null  object
 42  總負債/總淨值            11014 non-null  object
 43  負債比率               11014 non-null  float64
 44  淨值/資產              11014 non-null  float64
 45  長期資金適合率(A)         11014 non-null  object
 46  長短期借款              11014 non-null  object
 47  淨負債                11014 non-null  object
 48  借款依存度              11014 non-null  object
 49  或有負債/淨值            11014 non-null  object
 50  營業利益 /實收資本比        11014 non-null  object
 51  稅前純益 /實收資本         11014 non-null  object
 52  內部保留比率             11014 non-null  object
 53  股利支付率              11014 non-null  object
 54  公司編號               11014 non-null  int32
 55  年份                 11014 non-null  int32
 56  coid               6624 non-null   float64
 57  mdate              6624 non-null   float64
 58  tcri               6624 non-null   object
dtypes: float64(4), int32(3), int64(1), object(51)
memory usage: 4.8+ MB

In [7]:
merged_data

,公司,年/月,季別,合併(Y/N),月份,幣別,現金及約當現金,流動資產,資產總額,流動負債,...,或有負債/淨值,營業利益 /實收資本比,稅前純益 /實收資本,內部保留比率,股利支付率,公司編號,年份,coid,mdate,tcri
0,1101 台泥,2024/12,4,Y,12,NTD,"77,764,504","173,380,580","593,413,647","86,373,382",...,0,22.1,29.46,29.51,66.89,1101,2024,NaN,NaN,NaN
1,1101 台泥,2018/12,4,Y,12,NTD,"48,507,889","110,380,695","344,085,118","64,503,844",...,0,53.09,57.54,20.33,79.58,1101,2018,NaN,NaN,NaN
2,1101 台泥,2016/12,4,Y,12,NTD,"28,179,758","77,884,012","266,988,696","55,104,919",...,0.34,35.3,31.19,15.8,84.2,1101,2016,NaN,NaN,NaN
3,1101 台泥,2015/12,4,Y,12,NTD,"38,977,360","90,593,376","293,066,355","68,083,832",...,0.34,26.2,23.47,14.98,85.02,1101,2015,NaN,NaN,NaN
4,1101 台泥,2022/12,4,Y,12,NTD,"88,842,494","175,624,058","460,808,961","75,209,411",...,0,1.58,9.03,27.55,65.98,1101,2022,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11009,9958 世紀鋼,2016/12,4,Y,12,NTD,"466,056","3,825,398","6,410,651","1,696,644",...,0,8.67,5.81,23.9,76.1,9958,2016,9958.0,2016.0,7
11010,9958 世紀鋼,2014/12,4,Y,12,NTD,"83,546","3,909,149","6,169,744","1,223,401",...,0,7.32,4.56,71.82,28.18,9958,2014,9958.0,2014.0,7
11011,9958 世紀鋼,2022/12,4,Y,12,NTD,"1,312,925","11,725,747","29,360,142","8,642,269",...,0,3.98,7.12,68.43,31.57,9958,2022,9958.0,2022.0,5
11012,9958 世紀鋼,2024/12,4,Y,12,NTD,"6,574,329","19,298,266","41,319,667","5,990,814",...,0,115.66,114.21,41.59,58.41,9958,2024,9958.0,2024.0,5
11013,9958 世紀鋼,2021/12,4,Y,12,NTD,"1,488,247","10,826,420","26,868,051","7,242,838",...,0,75.6,82.64,44.86,55.14,9958,2021,9958.0,2021.0,5

### change object(D->10 C->11)

In [8]:
columns_to_skip = merged_data.columns[:5].tolist()

object_columns = merged_data.iloc[:, 5:].select_dtypes(include=['object']).columns.tolist()

merged_data['tcri'] = merged_data['tcri'].replace({
    'D': 10,
    'C': 11
})

def simple_convert(df, columns):
    df_converted = df.copy()
    
    for col in columns:

        df_converted[col] = df_converted[col].astype(str).str.replace(',', '').str.replace(' ', '')
        df_converted[col] = pd.to_numeric(df_converted[col], errors='coerce')
        original_non_null = df[col].notna().sum()
        new_non_null = df_converted[col].notna().sum()
        conversion_rate = new_non_null / original_non_null * 100 if original_non_null > 0 else 0
    
    return df_converted
merged_data = simple_convert(merged_data, object_columns)

In [9]:
pd.set_option('display.float_format', '{:.2f}'.format)
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11014 entries, 0 to 11013
Data columns (total 59 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   公司                 11014 non-null  object
 1   年/月                11014 non-null  object
 2   季別                 11014 non-null  int64
 3   合併(Y/N)            11014 non-null  object
 4   月份                 11014 non-null  int32
 5   幣別                 0 non-null      float64
 6   現金及約當現金            11013 non-null  float64
 7   流動資產               10673 non-null  float64
 8   資產總額               11014 non-null  int64
 9   流動負債               10673 non-null  float64
 10  負債總額               11014 non-null  int64
 11  普通股股本              11014 non-null  int64
 12  股本                 11014 non-null  int64
 13  資本公積合計             11014 non-null  int64
 14  保留盈餘               11014 non-null  int64
 15  股東權益總額             11014 non-null  int64
 16  營業收入淨額             10994 non-null  float64
 17  營業成本               10719 non-null  float64
 18  營業毛利               10719 non-null  float64
 19  營業費用               10994 non-null  float64
 20  營運資金               10670 non-null  float64
 21  研究發展費              10377 non-null  float64
 22  預期信用減損（損失）利益－營業費用  6812 non-null   float64
 23  營業利益               10719 non-null  float64
 24  財務成本               10685 non-null  float64
 25  稅前淨利               10994 non-null  float64
 26  稅前息前淨利             10967 non-null  float64
 27  來自營運之現金流量          10993 non-null  float64
 28  投資活動之現金流量          10993 non-null  float64
 29  籌資活動之現金流量          10993 non-null  float64
 30  Tobins Q           11013 non-null  float64
 31  財務槓桿度              9328 non-null   float64
 32  營運槓桿度              9201 non-null   float64
 33  利息保障倍數             10334 non-null  float64
 34  ROA－綜合損益           10913 non-null  float64
 35  ROE－綜合損益           10913 non-null  float64
 36  現金流量允當比            10409 non-null  float64
 37  現金再投資比             10453 non-null  float64
 38  流動比率               10673 non-null  float64
 39  速動比率               10672 non-null  float64
 40  利息支出率              10796 non-null  float64
 41  利息支出率(B)           10630 non-null  float64
 42  總負債/總淨值            11014 non-null  float64
 43  負債比率               11014 non-null  float64
 44  淨值/資產              11014 non-null  float64
 45  長期資金適合率(A)         10670 non-null  float64
 46  長短期借款              11013 non-null  float64
 47  淨負債                10639 non-null  float64
 48  借款依存度              10672 non-null  float64
 49  或有負債/淨值            10643 non-null  float64
 50  營業利益 /實收資本比        10719 non-null  float64
 51  稅前純益 /實收資本         10994 non-null  float64
 52  內部保留比率             9231 non-null   float64
 53  股利支付率              10796 non-null  float64
 54  公司編號               11014 non-null  int32
 55  年份                 11014 non-null  int32
 56  coid               6624 non-null   float64
 57  mdate              6624 non-null   float64
 58  tcri               6624 non-null   float64
dtypes: float64(45), int32(3), int64(8), object(3)
memory usage: 4.8+ MB

In [10]:
merged_data[merged_data['tcri'] == 10]

,公司,年/月,季別,合併(Y/N),月份,幣別,現金及約當現金,流動資產,資產總額,流動負債,...,或有負債/淨值,營業利益 /實收資本比,稅前純益 /實收資本,內部保留比率,股利支付率,公司編號,年份,coid,mdate,tcri
112,1213 大飲,2023/12,4,Y,12,NaN,1125.00,32646.00,819325,554815.00,...,0.00,-25.06,-20.93,NaN,0.00,1213,2023,1213.00,2023.00,10.00
645,1418 東華,2017/12,4,Y,12,NaN,40125.00,312558.00,1581782,1169539.00,...,0.00,-51.07,-55.92,NaN,0.00,1418,2017,1418.00,2017.00,10.00
649,1418 東華,2019/12,4,Y,12,NaN,205371.00,416111.00,2456023,291753.00,...,0.00,-33.86,-37.68,NaN,0.00,1418,2019,1418.00,2019.00,10.00
650,1418 東華,2020/12,4,Y,12,NaN,56186.00,177008.00,2232986,121582.00,...,0.00,-48.08,-38.93,NaN,0.00,1418,2020,1418.00,2020.00,10.00
652,1418 東華,2018/12,4,Y,12,NaN,239665.00,361499.00,2668543,61586.00,...,0.00,-35.58,-38.32,NaN,0.00,1418,2018,1418.00,2018.00,10.00
653,1418 東華,2016/12,4,Y,12,NaN,45288.00,464794.00,1772056,1126152.00,...,0.00,-12.78,-13.42,NaN,0.00,1418,2016,1418.00,2016.00,10.00
654,1418 東華,2021/12,4,Y,12,NaN,352852.00,378103.00,3555900,15259.00,...,0.00,-43.22,-28.09,NaN,0.00,1418,2021,1418.00,2021.00,10.00
853,1449 佳和,2014/12,4,Y,12,NaN,143612.00,2136258.00,5117915,1752513.00,...,3.85,-30.69,2.13,100.00,0.00,1449,2014,1449.00,2014.00,10.00
2383,2025 千興,2015/12,4,Y,12,NaN,126734.00,1120481.00,2573705,1410185.00,...,0.00,-9.90,-12.65,NaN,0.00,2025,2015,2025.00,2015.00,10.00
2384,2025 千興,2019/12,4,N,12,NaN,155627.00,888845.00,1920233,727909.00,...,0.00,-7.01,-6.32,NaN,0.00,2025,2019,2025.00,2019.00,10.00
2389,2025 千興,2020/12,4,N,12,NaN,20588.00,825076.00,1754625,872527.00,...,0.00,-7.90,-7.46,NaN,0.00,2025,2020,2025.00,2020.00,10.00
2390,2025 千興,2016/12,4,Y,12,NaN,132973.00,913837.00,2245159,1005940.00,...,0.00,1.65,2.85,100.00,0.00,2025,2016,2025.00,2016.00,10.00
2405,2028 威致,2018/12,4,N,12,NaN,115430.00,2644398.00,6757822,2342071.00,...,0.00,16.91,15.53,100.00,0.00,2028,2018,2028.00,2018.00,10.00
2406,2028 威致,2017/12,4,N,12,NaN,143323.00,2202764.00,6543773,2012359.00,...,0.00,21.93,19.87,100.00,0.00,2028,2017,2028.00,2017.00,10.00
2408,2028 威致,2015/12,4,N,12,NaN,33301.00,1063339.00,5214135,1193093.00,...,0.00,-15.87,-20.13,NaN,0.00,2028,2015,2028.00,2015.00,10.00
2411,2028 威致,2019/12,4,N,12,NaN,38925.00,2020503.00,6092207,1640607.00,...,0.00,5.58,5.88,100.00,0.00,2028,2019,2028.00,2019.00,10.00
2413,2028 威致,2016/12,4,N,12,NaN,199629.00,1938505.00,6253342,2162280.00,...,0.00,2.11,0.51,100.00,0.00,2028,2016,2028.00,2016.00,10.00
3082,2342 茂矽,2015/12,4,Y,12,NaN,269353.00,1252168.00,2593483,1486714.00,...,0.00,-14.58,-26.52,NaN,0.00,2342,2015,2342.00,2015.00,10.00
3088,2342 茂矽,2016/12,4,Y,12,NaN,378347.00,1131591.00,2262562,1296955.00,...,0.00,1.39,-2.66,NaN,0.00,2342,2016,2342.00,2016.00,10.00
3090,2342 茂矽,2014/12,4,Y,12,NaN,606440.00,1338810.00,4069581,1933731.00,...,0.00,-21.80,-10.95,NaN,0.00,2342,2014,2342.00,2014.00,10.00
3092,2342 茂矽,2017/12,4,Y,12,NaN,903628.00,2230309.00,2659335,1214560.00,...,0.00,5.58,-3.18,NaN,0.00,2342,2017,2342.00,2017.00,10.00
3411,2380 虹光,2024/12,4,Y,12,NaN,353928.00,1212809.00,1864841,1320297.00,...,0.00,-17.59,-18.37,NaN,0.00,2380,2024,2380.00,2024.00,10.00
4251,2491 吉祥全,2017/12,4,Y,12,NaN,13317.00,582614.00,2116323,211923.00,...,120.08,-1.44,4.21,100.00,0.00,2491,2017,2491.00,2017.00,10.00
4252,2491 吉祥全,2015/12,4,Y,12,NaN,21719.00,635574.00,2227333,1438595.00,...,0.00,-11.02,-0.66,100.00,0.00,2491,2015,2491.00,2015.00,10.00
4255,2491 吉祥全,2016/12,4,Y,12,NaN,8105.00,592698.00,2155799,213214.00,...,131.01,-7.57,-5.70,NaN,0.00,2491,2016,2491.00,2016.00,10.00
4257,2491 吉祥全,2018/12,4,Y,12,NaN,19005.00,582536.00,2088398,1347858.00,...,121.96,-3.02,-5.04,NaN,0.00,2491,2018,2491.00,2018.00,10.00
4258,2491 吉祥全,2014/12,4,Y,12,NaN,22842.00,735682.00,2364999,1527861.00,...,0.00,-23.92,23.98,100.00,0.00,2491,2014,2491.00,2014.00,10.00
4294,2496 卓越,2015/12,4,N,12,NaN,50627.00,119921.00,134833,88329.00,...,0.00,-6.13,-5.94,NaN,0.00,2496,2015,2496.00,2015.00,10.00
4298,2496 卓越,2014/12,4,N,12,NaN,26489.00,112769.00,130949,34665.00,...,0.00,-24.17,-23.16,NaN,0.00,2496,2014,2496.00,2014.00,10.00
4824,2633 台灣高鐵,2014/12,4,N,12,NaN,1332151.00,57324949.00,501660707,10995461.00,...,0.00,11.29,2.54,100.00,0.00,2633,2014,2633.00,2014.00,10.00
5455,2911 麗嬰房,2024/12,4,Y,12,NaN,805448.00,2049979.00,3903233,2442698.00,...,0.00,-41.57,-39.69,NaN,0.00,2911,2024,2911.00,2024.00,10.00
5684,3018 隆銘綠能,2021/12,4,Y,12,NaN,162296.00,1095932.00,1523542,832989.00,...,13.00,-15.23,-29.22,NaN,0.00,3018,2021,3018.00,2021.00,10.00
5939,3043 科風,2016/12,4,Y,12,NaN,139148.00,892512.00,1357298,1269047.00,...,0.00,-6.10,-4.26,NaN,0.00,3043,2016,3043.00,2016.00,10.00
5943,3043 科風,2017/12,4,Y,12,NaN,115246.00,793983.00,1221991,1174119.00,...,0.00,1.55,-2.73,NaN,0.00,3043,2017,3043.00,2017.00,10.00
6024,3051 力特,2014/12,4,Y,12,NaN,369533.00,3496637.00,11532117,2191734.00,...,0.00,15.54,16.62,100.00,0.00,3051,2014,3051.00,2014.00,10.00
6028,3051 力特,2020/12,4,Y,12,NaN,172404.00,5267402.00,8807966,1452729.00,...,0.00,3.64,0.96,100.00,0.00,3051,2020,3051.00,2020.00,10.00
6029,3051 力特,2016/12,4,Y,12,NaN,967145.00,2969583.00,10087323,2380038.00,...,0.00,3.11,-3.92,NaN,0.00,3051,2016,3051.00,2016.00,10.00
6030,3051 力特,2019/12,4,Y,12,NaN,337148.00,2291165.00,8966545,2056577.00,...,0.00,4.48,-3.90,NaN,0.00,3051,2019,3051.00,2019.00,10.00
6031,3051 力特,2017/12,4,Y,12,NaN,597199.00,2455157.00,9148117,1217259.00,...,0.00,8.38,-2.66,NaN,0.00,3051,2017,3051.00,2017.00,10.00
6032,3051 力特,2015/12,4,Y,12,NaN,894196.00,3427712.00,11123674,1888045.00,...,0.00,10.04,9.37,100.00,0.00,3051,2015,3051.00,2015.00,10.00
6033,3051 力特,2018/12,4,Y,12,NaN,421409.00,2140163.00,8628786,1912806.00,...,0.00,4.77,-1.34,NaN,0.00,3051,2018,3051.00,2018.00,10.00
6195,3149 正達,2016/12,4,Y,12,NaN,940593.00,2413045.00,6102261,3342843.00,...,0.00,-91.51,-27.44,NaN,0.00,3149,2016,3149.00,2016.00,10.00
6531,3481 群創,2014/12,4,Y,12,NaN,70989741.00,189380812.00,482516555,199135498.00,...,0.00,28.30,22.64,67.95,32.05,3481,2014,3481.00,2014.00,10.00
6767,3593 力銘,2024/12,4,Y,12,NaN,57724.00,544958.00,1465376,887154.00,...,0.00,-21.64,-21.63,NaN,0.00,3593,2024,3593.00,2024.00,10.00
6944,3701 大眾控,2016/12,4,Y,12,NaN,1060295.00,5764609.00,9362031,5840940.00,...,0.00,0.97,8.83,100.00,0.00,3701,2016,3701.00,2016.00,10.00
7176,4414 如興,2022/12,4,Y,12,NaN,478616.00,9212599.00,15185726,10005377.00,...,6.47,-29.82,-55.88,NaN,0.00,4414,2022,4414.00,2022.00,10.00
7749,4960 誠美材,2020/12,4,Y,12,NaN,412618.00,6249367.00,14571675,4595888.00,...,24.57,-4.05,-1.36,NaN,0.00,4960,2020,4960.00,2020.00,10.00
7754,4960 誠美材,2018/12,4,Y,12,NaN,3105426.00,13498543.00,27233917,12629552.00,...,0.00,-9.12,-16.12,NaN,0.00,4960,2018,4960.00,2018.00,10.00
8712,6225 天瀚,2015/12,4,Y,12,NaN,9436.00,62886.00,68793,47154.00,...,0.00,-6.09,-4.28,NaN,0.00,6225,2015,6225.00,2015.00,10.00
8714,6225 天瀚,2016/12,4,Y,12,NaN,5431.00,20215.00,23955,15927.00,...,0.00,-3.00,-2.42,NaN,0.00,6225,2016,6225.00,2016.00,10.00
8715,6225 天瀚,2014/12,4,Y,12,NaN,40274.00,144883.00,194701,150348.00,...,0.00,-13.23,-13.72,NaN,0.00,6225,2014,6225.00,2014.00,10.00
8716,6225 天瀚,2018/12,4,Y,12,NaN,9638.00,18034.00,20097,9854.00,...,0.00,-1.74,-1.60,NaN,0.00,6225,2018,6225.00,2018.00,10.00
8717,6225 天瀚,2020/12,4,Y,12,NaN,12958.00,22430.00,23980,4295.00,...,0.00,-0.51,-0.53,NaN,0.00,6225,2020,6225.00,2020.00,10.00
8719,6225 天瀚,2021/12,4,Y,12,NaN,4088.00,23370.00,24540,8945.00,...,0.00,-0.88,-0.86,NaN,0.00,6225,2021,6225.00,2021.00,10.00
8720,6225 天瀚,2017/12,4,Y,12,NaN,4275.00,16188.00,18577,11065.00,...,0.00,-1.78,-1.29,NaN,0.00,6225,2017,6225.00,2017.00,10.00
8721,6225 天瀚,2019/12,4,Y,12,NaN,5277.00,15260.00,17267,5248.00,...,0.00,-1.13,-0.73,NaN,0.00,6225,2019,6225.00,2019.00,10.00
10002,8101 華冠,2021/12,4,Y,12,NaN,103225.00,383626.00,1073854,505630.00,...,0.00,-25.94,0.91,100.00,0.00,8101,2021,8101.00,2021.00,10.00
10005,8101 華冠,2022/12,4,Y,12,NaN,9244.00,254743.00,781059,377973.00,...,0.00,-38.91,-22.25,NaN,0.00,8101,2022,8101.00,2022.00,10.00
10012,8101 華冠,2023/12,4,Y,12,NaN,6177.00,126040.00,608538,281483.00,...,0.00,-25.62,-27.95,NaN,0.00,8101,2023,8101.00,2023.00,10.00

### Delete no tcri

In [11]:
merged_data_clean = merged_data.dropna(subset=['tcri'])
#merged_data_clean = merged_data
merged_data_clean

,公司,年/月,季別,合併(Y/N),月份,幣別,現金及約當現金,流動資產,資產總額,流動負債,...,或有負債/淨值,營業利益 /實收資本比,稅前純益 /實收資本,內部保留比率,股利支付率,公司編號,年份,coid,mdate,tcri
22,1103 嘉泥,2022/12,4,Y,12,NaN,4463396.00,10395347.00,36454234,3431484.00,...,1.44,-5.10,-1.57,NaN,-128.35,1103,2022,1103.00,2022.00,6.00
23,1103 嘉泥,2016/12,4,Y,12,NaN,2341044.00,9443483.00,26128917,1981486.00,...,2.57,-5.90,1.02,-522.59,622.59,1103,2016,1103.00,2016.00,6.00
24,1103 嘉泥,2018/12,4,Y,12,NaN,1969663.00,11150914.00,31985629,3195396.00,...,2.02,-1.34,5.52,-10.29,110.29,1103,2018,1103.00,2018.00,6.00
25,1103 嘉泥,2019/12,4,Y,12,NaN,2066897.00,10657604.00,38720634,3700460.00,...,1.62,-5.61,12.72,40.52,59.48,1103,2019,1103.00,2019.00,6.00
26,1103 嘉泥,2020/12,4,Y,12,NaN,3375981.00,11726520.00,40646227,3042465.00,...,1.44,10.62,27.18,38.81,61.19,1103,2020,1103.00,2020.00,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11009,9958 世紀鋼,2016/12,4,Y,12,NaN,466056.00,3825398.00,6410651,1696644.00,...,0.00,8.67,5.81,23.90,76.10,9958,2016,9958.00,2016.00,7.00
11010,9958 世紀鋼,2014/12,4,Y,12,NaN,83546.00,3909149.00,6169744,1223401.00,...,0.00,7.32,4.56,71.82,28.18,9958,2014,9958.00,2014.00,7.00
11011,9958 世紀鋼,2022/12,4,Y,12,NaN,1312925.00,11725747.00,29360142,8642269.00,...,0.00,3.98,7.12,68.43,31.57,9958,2022,9958.00,2022.00,5.00
11012,9958 世紀鋼,2024/12,4,Y,12,NaN,6574329.00,19298266.00,41319667,5990814.00,...,0.00,115.66,114.21,41.59,58.41,9958,2024,9958.00,2024.00,5.00
11013,9958 世紀鋼,2021/12,4,Y,12,NaN,1488247.00,10826420.00,26868051,7242838.00,...,0.00,75.60,82.64,44.86,55.14,9958,2021,9958.00,2021.00,5.00

### delete mdate coid first 5 column

In [12]:
columns_to_drop = ['mdate', 'coid']
existing_columns_to_drop = [col for col in columns_to_drop if col in merged_data_clean.columns]
merged_data_clean = merged_data_clean.drop(columns=existing_columns_to_drop)

In [13]:
columns_to_drop = merged_data_clean.columns[:6].tolist()

merged_data_final = merged_data_clean.drop(columns=columns_to_drop)

company_col = '公司編號' if '公司編號' in merged_data_final.columns else 'coid'
year_col = '年份' if '年份' in merged_data_final.columns else 'mdate'

other_columns = [col for col in merged_data_final.columns if col not in [company_col, year_col]]
new_column_order = [company_col, year_col] + other_columns

merged_data_final = merged_data_final[new_column_order]

for i, col in enumerate(merged_data_final.columns):
    print(f"  {i+1:2d}. {col}")

   1. 公司編號
   2. 年份
   3. 現金及約當現金
   4. 流動資產
   5. 資產總額
   6. 流動負債
   7. 負債總額
   8. 普通股股本
   9. 股本
  10. 資本公積合計
  11. 保留盈餘
  12. 股東權益總額
  13. 營業收入淨額
  14. 營業成本
  15. 營業毛利
  16. 營業費用
  17. 營運資金
  18. 研究發展費
  19. 預期信用減損（損失）利益－營業費用
  20. 營業利益
  21. 財務成本
  22. 稅前淨利
  23. 稅前息前淨利
  24. 來自營運之現金流量
  25. 投資活動之現金流量
  26. 籌資活動之現金流量
  27. Tobins Q
  28. 財務槓桿度
  29. 營運槓桿度
  30. 利息保障倍數
  31. ROA－綜合損益
  32. ROE－綜合損益
  33. 現金流量允當比
  34. 現金再投資比
  35. 流動比率
  36. 速動比率
  37. 利息支出率
  38. 利息支出率(B)
  39. 總負債/總淨值
  40. 負債比率
  41. 淨值/資產
  42. 長期資金適合率(A)
  43. 長短期借款
  44. 淨負債
  45. 借款依存度
  46. 或有負債/淨值
  47. 營業利益 /實收資本比
  48. 稅前純益 /實收資本
  49. 內部保留比率
  50. 股利支付率
  51. tcri

In [14]:
merged_data_final

,公司編號,年份,現金及約當現金,流動資產,資產總額,流動負債,負債總額,普通股股本,股本,資本公積合計,...,長期資金適合率(A),長短期借款,淨負債,借款依存度,或有負債/淨值,營業利益 /實收資本比,稅前純益 /實收資本,內部保留比率,股利支付率,tcri
22,1103,2022,4463396.00,10395347.00,36454234,3431484.00,14454807,7747805,7747805,1238426,...,607.19,10173996.00,356009.00,46.25,1.44,-5.10,-1.57,NaN,-128.35,6.00
23,1103,2016,2341044.00,9443483.00,26128917,1981486.00,10315659,7747805,7747805,617579,...,1115.35,7902023.00,2775186.00,49.97,2.57,-5.90,1.02,-522.59,622.59,6.00
24,1103,2018,1969663.00,11150914.00,31985629,3195396.00,11065810,7747805,7747805,703931,...,778.94,7735152.00,1847995.00,36.98,2.02,-1.34,5.52,-10.29,110.29,6.00
25,1103,2019,2066897.00,10657604.00,38720634,3700460.00,15044409,7747805,7747805,847377,...,484.60,10049179.00,312847.00,42.44,1.62,-5.61,12.72,40.52,59.48,6.00
26,1103,2020,3375981.00,11726520.00,40646227,3042465.00,15628878,7747805,7747805,960402,...,545.39,11000781.00,-245316.00,43.97,1.44,10.62,27.18,38.81,61.19,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11009,9958,2016,466056.00,3825398.00,6410651,1696644.00,3847156,1855581,1855581,69141,...,214.48,2917938.00,2451882.00,113.83,0.00,8.67,5.81,23.90,76.10,7.00
11010,9958,2014,83546.00,3909149.00,6169744,1223401.00,3951835,1819197,1819197,69707,...,237.13,3084643.00,3000819.00,139.08,0.00,7.32,4.56,71.82,28.18,7.00
11011,9958,2022,1312925.00,11725747.00,29360142,8642269.00,19119083,2323964,2323964,3038789,...,140.95,10414674.00,7224739.00,101.70,0.00,3.98,7.12,68.43,31.57,5.00
11012,9958,2024,6574329.00,19298266.00,41319667,5990814.00,18853036,2568967,2568967,6521497,...,190.35,11340464.00,2496445.00,50.48,0.00,115.66,114.21,41.59,58.41,5.00
11013,9958,2021,1488247.00,10826420.00,26868051,7242838.00,16786460,2312789,2312789,2948844,...,178.70,9154078.00,6797863.00,90.80,0.00,75.60,82.64,44.86,55.14,5.00

In [15]:
merged_data_final = merged_data_final.sort_values(['公司編號', '年份'])
merged_data_final

,公司編號,年份,現金及約當現金,流動資產,資產總額,流動負債,負債總額,普通股股本,股本,資本公積合計,...,長期資金適合率(A),長短期借款,淨負債,借款依存度,或有負債/淨值,營業利益 /實收資本比,稅前純益 /實收資本,內部保留比率,股利支付率,tcri
30,1103,2014,3163688.00,12878015.00,33666479,3366245.00,14384421,7768285,7768285,570096,...,919.64,11511699.00,2968412.00,59.70,0.00,-3.33,0.12,-1325.99,1425.99,6.00
27,1103,2015,1829306.00,10683575.00,27383042,1526371.00,13336696,7768285,7768285,605975,...,1034.26,10968921.00,5061597.00,78.09,3.07,5.26,2.51,65.02,34.98,6.00
23,1103,2016,2341044.00,9443483.00,26128917,1981486.00,10315659,7747805,7747805,617579,...,1115.35,7902023.00,2775186.00,49.97,2.57,-5.90,1.02,-522.59,622.59,6.00
31,1103,2017,1803189.00,9106166.00,28317986,2317056.00,9057146,7747805,7747805,642168,...,857.07,7029533.00,2175513.00,36.50,2.22,-2.96,13.96,56.73,43.27,6.00
24,1103,2018,1969663.00,11150914.00,31985629,3195396.00,11065810,7747805,7747805,703931,...,778.94,7735152.00,1847995.00,36.98,2.02,-1.34,5.52,-10.29,110.29,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11005,9958,2020,1516780.00,6700626.00,17341360,4083299.00,8335875,2181725,2299898,2904329,...,167.08,2595912.00,150636.00,28.83,0.00,51.58,49.47,10.04,89.96,5.00
11013,9958,2021,1488247.00,10826420.00,26868051,7242838.00,16786460,2312789,2312789,2948844,...,178.70,9154078.00,6797863.00,90.80,0.00,75.60,82.64,44.86,55.14,5.00
11011,9958,2022,1312925.00,11725747.00,29360142,8642269.00,19119083,2323964,2323964,3038789,...,140.95,10414674.00,7224739.00,101.70,0.00,3.98,7.12,68.43,31.57,5.00
11007,9958,2023,2000598.00,14366181.00,35499125,8416971.00,21821723,2359661,2383471,3904711,...,148.95,14354659.00,10096761.00,104.95,0.00,82.90,71.24,28.52,71.48,5.00
11012,9958,2024,6574329.00,19298266.00,41319667,5990814.00,18853036,2568967,2568967,6521497,...,190.35,11340464.00,2496445.00,50.48,0.00,115.66,114.21,41.59,58.41,5.00

In [16]:
merged_data_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6624 entries, 30 to 11012
Data columns (total 51 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   公司編號               6624 non-null   int32
 1   年份                 6624 non-null   int32
 2   現金及約當現金            6624 non-null   float64
 3   流動資產               6624 non-null   float64
 4   資產總額               6624 non-null   int64
 5   流動負債               6624 non-null   float64
 6   負債總額               6624 non-null   int64
 7   普通股股本              6624 non-null   int64
 8   股本                 6624 non-null   int64
 9   資本公積合計             6624 non-null   int64
 10  保留盈餘               6624 non-null   int64
 11  股東權益總額             6624 non-null   int64
 12  營業收入淨額             6624 non-null   float64
 13  營業成本               6624 non-null   float64
 14  營業毛利               6624 non-null   float64
 15  營業費用               6624 non-null   float64
 16  營運資金               6624 non-null   float64
 17  研究發展費              6392 non-null   float64
 18  預期信用減損（損失）利益－營業費用  4187 non-null   float64
 19  營業利益               6624 non-null   float64
 20  財務成本               6624 non-null   float64
 21  稅前淨利               6624 non-null   float64
 22  稅前息前淨利             6624 non-null   float64
 23  來自營運之現金流量          6624 non-null   float64
 24  投資活動之現金流量          6624 non-null   float64
 25  籌資活動之現金流量          6624 non-null   float64
 26  Tobins Q           6624 non-null   float64
 27  財務槓桿度              5779 non-null   float64
 28  營運槓桿度              5668 non-null   float64
 29  利息保障倍數             6433 non-null   float64
 30  ROA－綜合損益           6623 non-null   float64
 31  ROE－綜合損益           6623 non-null   float64
 32  現金流量允當比            6517 non-null   float64
 33  現金再投資比             6588 non-null   float64
 34  流動比率               6624 non-null   float64
 35  速動比率               6624 non-null   float64
 36  利息支出率              6624 non-null   float64
 37  利息支出率(B)           6624 non-null   float64
 38  總負債/總淨值            6624 non-null   float64
 39  負債比率               6624 non-null   float64
 40  淨值/資產              6624 non-null   float64
 41  長期資金適合率(A)         6624 non-null   float64
 42  長短期借款              6624 non-null   float64
 43  淨負債                6624 non-null   float64
 44  借款依存度              6624 non-null   float64
 45  或有負債/淨值            6622 non-null   float64
 46  營業利益 /實收資本比        6624 non-null   float64
 47  稅前純益 /實收資本         6624 non-null   float64
 48  內部保留比率             5169 non-null   float64
 49  股利支付率              6624 non-null   float64
 50  tcri               6624 non-null   float64
dtypes: float64(42), int32(2), int64(7)
memory usage: 2.6 MB

In [17]:
merged_data_final.describe().T

,count,mean,std,min,25%,50%,75%,max
公司編號,6624.00,3592.26,2199.89,1103.00,2014.00,2633.00,4942.00,9958.00
年份,6624.00,2019.06,3.12,2014.00,2016.00,2019.00,2022.00,2024.00
現金及約當現金,6624.00,2030568.19,6681041.89,1125.00,319313.75,700943.50,1517210.50,149427959.00
流動資產,6624.00,8676515.57,29273748.10,15260.00,1446379.25,2779874.00,6561823.75,683292033.00
資產總額,6624.00,18772394.16,71548731.98,17267.00,2763590.00,5434440.50,12428527.25,1657801534.00
流動負債,6624.00,5895339.38,28374650.79,776.00,654168.00,1491492.00,3770967.75,793421493.00
負債總額,6624.00,11550074.48,62372827.08,4946.00,944547.25,2295347.00,5883270.00,1607622209.00
普通股股本,6624.00,3387310.89,7638767.97,142719.00,870909.50,1489517.50,3004308.50,105596201.00
股本,6624.00,3399694.15,7709701.07,157600.00,875460.00,1490550.00,3005579.00,105596201.00
資本公積合計,6624.00,1190792.65,5304743.16,-207088.00,59144.75,305537.50,878949.75,105919710.00
保留盈餘,6624.00,2141338.76,7688968.61,-46658745.00,187311.00,724805.00,1799414.75,280077242.00
股東權益總額,6624.00,7222319.68,18043966.48,2927.00,1610278.25,2993183.50,6309343.00,343785963.00
營業收入淨額,6624.00,9694843.58,29929935.84,11.00,1451852.00,3111254.00,7313205.50,646261954.00
營業成本,6624.00,8170401.16,26738373.27,-4032.00,1032336.25,2420231.50,5929306.25,612924800.00
營業毛利,6624.00,1524442.42,5449960.05,-58604462.00,251699.00,610933.50,1317295.25,230170119.00
營業費用,6624.00,1046435.85,2289195.51,7909.00,226312.50,425831.50,937629.75,32681953.00
營運資金,6624.00,2781176.19,9914050.60,-110129460.00,550106.25,1233756.00,2582510.50,262648808.00
研究發展費,6392.00,229100.37,915116.87,0.00,3083.25,50832.50,149718.00,16028319.00
預期信用減損（損失）利益－營業費用,4187.00,7340.54,97834.58,-326032.00,-135.50,0.00,2267.00,4778808.00
營業利益,6624.00,479630.46,4533921.42,-71751974.00,-17983.50,141819.00,454581.25,220698167.00
財務成本,6624.00,109502.99,444757.96,0.00,4891.75,18164.50,57614.00,9556030.00
稅前淨利,6624.00,578180.72,4532573.55,-31838025.00,18257.50,198185.50,545013.50,233620714.00
稅前息前淨利,6624.00,687683.71,4647606.14,-27876062.00,37276.00,225294.50,603326.25,236018505.00
來自營運之現金流量,6624.00,905898.37,6458144.65,-64409953.00,1445.00,215922.00,646807.25,210067260.00
投資活動之現金流量,6624.00,-674957.27,4779001.79,-141108194.00,-441916.25,-125219.50,-4997.25,73301769.00
籌資活動之現金流量,6624.00,-141428.40,3552160.09,-99260726.00,-315306.50,-59028.00,170145.00,50257136.00
Tobins Q,6624.00,1.18,1.12,0.02,0.72,0.92,1.29,34.68
財務槓桿度,5779.00,0.35,72.94,-5215.02,0.99,1.03,1.13,998.31
營運槓桿度,5668.00,5.66,166.01,-5716.41,1.03,1.89,3.94,10160.76
利息保障倍數,6433.00,1433.03,37404.96,-52212.75,1.75,9.84,33.85,1750954.00
ROA－綜合損益,6623.00,2.93,8.78,-122.36,-0.08,2.92,6.46,76.71
ROE－綜合損益,6623.00,4.89,18.38,-315.90,-0.17,5.55,12.18,162.46
現金流量允當比,6517.00,35.82,1368.26,-96151.45,23.18,71.61,115.54,13547.99
現金再投資比,6588.00,1.88,13.66,-232.86,-1.92,2.37,6.78,216.95
流動比率,6624.00,359.25,1518.65,5.88,135.67,183.69,285.39,71149.48
速動比率,6624.00,238.49,789.02,0.43,68.26,114.32,197.56,18744.78
利息支出率,6624.00,-189.96,17268.97,-1393110.22,0.04,4.24,15.27,137412.37
利息支出率(B),6624.00,3.67,77.24,0.00,0.16,0.56,1.36,5851.14
總負債/總淨值,6624.00,120.91,543.03,0.48,42.78,80.31,134.26,41648.92
負債比率,6624.00,43.73,19.09,0.48,29.97,44.54,57.31,99.76
淨值/資產,6624.00,56.27,19.09,0.24,42.69,55.46,70.03,99.52
長期資金適合率(A),6624.00,13816.37,173518.73,0.00,173.53,276.57,544.12,7004220.00
長短期借款,6624.00,5182598.65,19376095.51,0.00,237349.25,1057886.00,3351458.00,448566805.00
淨負債,6624.00,2562920.22,18085618.94,-303180654.00,-620767.00,153718.00,1800028.00,446539743.00
借款依存度,6624.00,61.96,210.77,0.00,10.85,39.84,79.95,15944.99
或有負債/淨值,6622.00,0.29,3.62,0.00,0.00,0.00,0.00,131.01
營業利益 /實收資本比,6624.00,17.16,40.67,-777.80,-1.21,9.09,28.00,631.99
稅前純益 /實收資本,6624.00,20.90,41.80,-219.72,1.33,12.76,32.38,669.00
內部保留比率,5169.00,9.27,879.10,-59557.14,15.89,37.27,64.65,100.00
股利支付率,6624.00,68.58,787.23,-3700.15,0.00,50.16,78.38,59657.14
tcri,6624.00,6.27,1.18,5.00,5.00,6.00,7.00,11.00

In [18]:
merged_data_final.to_csv('merge_data.csv', index=False, encoding='utf-8-sig')